### ISSUE TITLE
Font Josefin Sans not working

### ISSUE THREAD

**Issue by MegrezPines** [libass/libass#528] opened 2021-07-08 15:15 UTC
Well, I made a subtitle for a video, in which the default font of that subtitle is [Josefin Sans](https://fonts.google.com/specimen/Josefin+Sans) 
Here is the image when render using Handbrake (which use libass, ofc):
![image](https://user-images.githubusercontent.com/79367788/124945958-d1f1b080-e038-11eb-9968-d2c116ab1c2e.png)
Here is the image of the video when playback in Aegisub or render using Staxrip:
![image](https://user-images.githubusercontent.com/79367788/124946254-154c1f00-e039-11eb-9b36-b0504ced6707.png)
I decided to make an issue like this for a long time but until now, this is the most current project to have the font problem (easier to get example image, if you need more I will get more examples of more and more font, eg: 000GosmickSansTB and some more which I don't remember)

**Comment by TheOneric** [comment] 2021-07-08 20:05
This needs more info to be of use:

**Exact libass version in use?**  
Which exact libass version is showing this behaviour? If you encountered the bug on an old version of libass please retest with current git-master if possible.

**Did it work in earlier versions of libass?**
If so which was the last “good” version?

**System you encountered the bug on?**  
OS:  *(\*Linux, Mac, Windows, …)*  
CPU: *(32 or 64Bit AMD/Intel x86, ARM, POWER, …)*

**ASS-Sample**
Please provide a sufficient sample of the ASS-file to reproduce the behaviour.

At minimum this will be an excerpt of an ASS file; don't forget to also share
the used Styles not only the Dialogue line. The excerpt should basically be a
fully functional ASS file in itself.

**Reference Images**
You have to reference images for working and not working. This is good. But it is not clear what ASS-renderer you used for the “good” screenshot. Eg on Windows Aegisub can use either (one of the many different) VSFilter(s) _or_ libass. Check `Advanced → Video → Subtitle-Provider` in Aegisub's options. I don't know about Staxrip.


**Log - Very important**
Handbrake produces logs, we need them. If the working screenshot was also produced by libass, ideally we would want logs for this as well *(for Aegisub in the Toolbar: `Help → Log Window` (or something similar))*

**Comment by astiob** [comment] 2021-07-08 20:06
Am I right to assume you’re using current Windows 10? (Or specifically Creators Update/version 1703/build 15063 or newer.)

Josefin Sans is a variable font, so this may just be a duplicate of #386. But I’m not immediately closing this as a duplicate because the libass screenshot is _weird:_ it looks as if it’s not just selecting a wrong weight (the only thing variable in this font) or an entire wrong font, but also using wrong advance values. But I can’t rule out that this is a strange consequence of being unable to select the right font variation.

**Comment by MegrezPines** [comment] 2021-07-09 10:05
- Well as I mentioned before, I used Handbrake so it pretty hard to determine the version of libass it's using.
- My system is Windows 10 21H1 64bits version, i7-2670QM 
- The log file is attached to this comment. 
[chào mừng đến với internet.m4v 07-08-2021 21-48-31.txt](https://github.com/libass/libass/files/6790421/chao.m.ng.d.n.v.i.internet.m4v.07-08-2021.21-48-31.txt)
- Okay, about Aegisub can use either VSFilter (mod/original) and libass: 
> I can confirm that my Aegisub is using VSFilter, because Aegisub (the official version, not the modded version by other people who improved it when the project is dropped :v) will **crash if I open a video while libass mode is on**. If libass is on, but the ass doesn't indicate which video file to open (and if you can edit the subtitle file without opening a video?, ofc I don't do that) then it's good. 

The ass file is attached to this comment as a .txt, changed it back to .ass when you open it, because Github not supporting .ass file: [welcometotheinternet (2).txt](https://github.com/libass/libass/files/6790484/welcometotheinternet.2.txt) 
Here is the video before render, open in PotPlayer (does support VSFiter original (pretty sure but no way to check if it's support libass) but not modded version):
![image](https://user-images.githubusercontent.com/79367788/125061599-b1c4fe80-e0d7-11eb-828d-dc6516d0c0c8.png)

**Comment by astiob** [comment] 2021-07-09 16:35
By the way: you are the author of this file, right? You should know that even in VSFilter, this font doesn’t work before Windows 10 Creators Update. OpenType variable fonts are not supported before Windows 10 Creators Update. So I recommend that you avoid releasing any subtitles using this font. If you really like the look of this particular font, there are some tools (e. g. [VFIT](https://github.com/jonpalmisc/vfit), but I haven’t used it myself) to convert a variable font to a nonvariable one.

FWIW I tried a simple test on macOS libass and on Windows 7 VSFilter. “Josefin Sans” simply uses Arial/Helvetica. “Josefin Sans Thin” works (in both), as that’s the first name that happens to be declared in the font file or something. At no point do I see the very broken rendering from the original report. :-(

**Comment by astiob** [comment] 2021-07-09 16:42
The provided Handbrake log shows libass did supposedly find Josefin-Sans-Regular-Roman: this is probably due to using the `directwrite` font provider on Windows 10. But clearly (judging by the screenshot), it didn’t quite work correctly, which is probably explained by libass being oblivious to the font’s variable status: DirectWrite gave us the font, but we don’t know how to work with it.

**Comment by TheOneric** [comment] 2021-07-09 19:33
Thanks for the info!
I previously missed the font being an variable one; this is likely the root of the issue.

> Well as I mentioned before, I used Handbrake so it pretty hard to determine the version of libass it's using.

You can find out by the info provided by whomever you got the binary from *(and if you don't know how, at least state how you obtained the HandBrake binary)*. E.g. if you're using the builds published by the HandBrake project itself, then based on the build date in your log, you are using libass `0.14.0` *(effectively unpatched; just some adjustments for their custom build setup)*.

Now, trying to reproduce with Fontconfig *(2.13.1, deb rev2)* as system font provider, “Josefin Sans” get's selected:
```
Using font provider fontconfig
fontselect: (Josefin Sans, 400, 0) -> ~/.fonts/JosefinSans-VariableFont_wght.ttf, 196608, JosefinSans_400wght
```
but, unlike in your screenshot it has "normal" spacing and by the looks of it also "normal" medium weight. This is true for both libass `0.14.0` and current [`master`](https://github.com/libass/libass/commit/856824f94a95e30b477f4ff7f3badcafd41285f1).
It could be `0.14.0`'s DirectWrite provider is treating the file differently though. Speculating, it could eg be, that the font file sets the default weight to 0 or something else really small, but fontconfig and CoreText are using some name-based heuristic to deliever a higher weight instead.

But ofc, as astiob already wrote, variable fonts are currently unsupported in libass *(see #386)* and it will (likely never) be supported in VSFilters running on Windows before previously mentioned update, so sub-authors might want to avoid those.

**Comment by astiob** [comment] 2021-07-10 22:18
With libass b9f3468 (much newer than the one you may be using) in mpv on Windows 10, I see libass log that it’s selected the Regular variant but actually use the Thin variant. But it’s used correctly, without the weird character overlap in your screenshot.

So I’m going to close this as a “cannot reproduce” for the overlap part, and as “duplicate” (of #386) for the part where we’re unable to select the right stylistic variant.

To recap, we’re looking to fix variant selection in the future, but we recommend avoiding variable fonts for public softsub releases in any case.

> with Fontconfig _(2.13.1, deb rev2)_ […]
> 
> ```
> Using font provider fontconfig
> fontselect: (Josefin Sans, 400, 0) -> ~/.fonts/JosefinSans-VariableFont_wght.ttf, 196608, JosefinSans_400wght
> ```
> 
> […] it has […] by the looks of it […] "normal" medium weight.

Hold on. Aren’t you saying Fontconfig somehow makes variable fonts work? That’s interesting!

**Closed by astiob** 2021-07-10 22:18 UTC
Labels: fonts

**Comment by TheOneric** [comment] 2021-07-10 23:52
> Hold on. Aren’t you saying Fontconfig somehow makes variable fonts work?

No,not really. As shown before in #386, selecting by name does not work only via `\b` tags. Iiuc, in VSF the names are the *only* way to select. Also in current libass with fontconfig the `\b`-tags can only resolve to named variants and not actually make use of the continous spectrum provided by the variable font, see:
![grafik](https://user-images.githubusercontent.com/1668471/125178942-b7126e00-e1e9-11eb-9bfb-15a93977ee26.png)

As for this specific sample, I get the "normal" medium weight with fontconfig, but from your descriptions it sounds like CoreText and old/current DirectWrite use the “Thin”-variant. Leading me to speculate(!) that this differnce may be due to the default weight value set by the font itself.
![grafik](https://user-images.githubusercontent.com/1668471/125178953-df01d180-e1e9-11eb-83a7-33116f8e2530.png)

**Comment by MegrezPines** [comment] 2021-07-11 03:17
> You should know that even in VSFilter, this font doesn’t work before Windows 10 Creators Update. OpenType variable fonts are not supported before Windows 10 Creators Update. ... If you really like the look of this particular font, there are some tools (e. g. VFIT, but I haven’t used it myself) to convert a variable font to a non-variable one.

Okay, that's new to me. So that means if I want to use this font, I should install using the non-variable OpenType font file of Josefin in the zip file Google Fonts provided right?  

>  E.g. if you're using the builds published by the HandBrake project itself, then based on the build date in your log, you are using libass 0.14.0 (effectively unpatched; just some adjustments for their custom build setup).

Oh okay, yes I am currently using the official Handbrake binary. So if Handbrake's using the 0.14.0, which was made in 2017 (man, that's old) I wonder if they will ever update the 0.15.1 for Handbrake soon. Lemme see if I can contact or found a way to build it myself (hopeless)

> But ofc, as astiob already wrote, variable fonts are currently unsupported in libass (see #386) and it will (likely never) be supported in VSFilters running on Windows before previously mentioned update, so sub-authors might want to avoid those.

Well, I can't really force you to fix stuff of course, but I mean, currently, the latest Windows version has already support OpenType variable, and VSF 100% can handle and select and load that font up. _I just don't get it about what is different in the core of libass and VSF working mechanism, leading to libass end up selecting the different font (or the top font on the list of the whole family). I wonder if there ever be a solution apart from just install a non-variable OpenType font file._

> To recap, we’re looking to fix variant selection in the future, but we recommend avoiding variable fonts for public softsub releases in any case.

Thanks for your supports. I hope it will successfully be fixed, and I hope to understand how different the libass working mechanism from VSF one day.

**Comment by astiob** [comment] 2021-07-12 18:35
> _I just don't get it about what is different in the core of libass and VSF working mechanism, leading to libass end up selecting the different font_

> I hope to understand how different the libass working mechanism from VSF one day.

Well, the font handling of VSFilter and libass is just entirely different. VSFilter delegates all of its font work to GDI—part of Windows—which acts as a one-stop shop and does everything related to fonts and much more. libass is cross-platform and performs more advanced text processing, so it implements font handling on its own.
