### ISSUE TITLE
libass Ignores Border <0.25 When a Blur Tag is Applied

### ISSUE THREAD

**Issue by MadokaAyukawa** [libass/libass#354] opened 2019-10-19 01:28 UTC
When creating blur effects, libass seems to ignore a border <0.25, and instead of blurring just the border, will blur the body of the text as well, often rendering the text unreadable. VSFilter seems to ignore the border only when it is <0.0625.

This can result in incorrectly appearing subtitles when subs are created in Aegisub using VSFilter and then played with libass in the media player or transcoded with FFmpeg. The last version of FFmpeg that seems to not have this issue is 3.3.4.

**Comment by Nadahar** [comment] 2019-11-07 16:26
This seems to be a regression in [0.14.0](https://github.com/libass/libass/tree/0.14.0); meaning that it isn't present in [0.13.7](https://github.com/libass/libass/tree/0.13.7).

**Comment by wm4** [comment] 2019-11-07 16:30
Can you bisect the exact commit which caused this?

**Comment by MadokaAyukawa** [comment] 2019-11-07 17:17
Here is a sample file so that you can see the issue. Just load this into Aegisub and choose between VSFilter and libass in the advanced video options.

[Blur Issue Test File.zip](https://github.com/libass/libass/files/3820874/Blur.Issue.Test.File.zip)

**Comment by Nadahar** [comment] 2019-11-07 17:21
@wm4 I'm sorry, but that is hard for me to do without gaining a lot more knowledge about the project. Currently, FFmpeg builds with different libass versions has been used, so to do test this in the same way, I'd have to figure out how to build both libass and FFmpeg.

**Comment by astiob** [comment] 2019-11-07 17:26
This sounds like this might be a duplicate of #325 (and #308), which is already fixed in Git master. Could anyone confirm this?

**Comment by astiob** [comment] 2019-11-07 17:29
Sorry, #309 not 325. No idea why I typed that number.

**Comment by Nadahar** [comment] 2019-11-07 17:34
> Sorry, #309 not 325. No idea why I typed that number.
@astiob Hehe, you had me confused there for a minute. 

Yes, it seems like this is a duplicate of #308 and #309. The problem is that no release has been made with the fix, so it's still very much an issue despite that the problem has been resolved.

**Comment by astiob** [comment] 2019-11-07 17:55
We have a few more outstanding issues that I’d like to fix before releasing… But if that doesn’t happen after a while, then we should probably release as-is.

Anyway, since this issue has actually been fixed, I’m marking this report as closed. Sorry it went under the radar and spent 20 days in limbo.

**Closed by astiob** 2019-11-07 17:55 UTC
