### ISSUE TITLE
\fscx≤0 prevents the rest of the line from rendering, even after \fscx100

### ISSUE THREAD

**Issue by rcombs** [libass/libass#428] opened 2020-09-18 03:22 UTC
```
[Script Info]
; Script generated by Aegisub 8959-rcombs-local-bae0e529a
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1280
PlayResY: 720

[Aegisub Project Garbage]
Video File: ?dummy:23.976000:100000:1280:720:83:62:245:c
Video AR Value: 1.777778
Video Zoom Percent: 1.000000
Active Line: 5
Video Position: 1

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,100,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.02,0:00:05.02,Default,,0,0,0,,{\an4\pos(350,330)}A{\fscx0}B{\fsc}C
Dialogue: 0,0:00:00.02,0:00:05.02,Default,,0,0,0,,{\an4\pos(350,400)}ABC
Dialogue: 0,0:00:00.02,0:00:05.02,Default,,0,0,0,,{\an4\pos(350,470)}A{\fscx-10}B{\fsc}C
Dialogue: 0,0:00:00.02,0:00:05.02,Default,,0,0,0,,{\an5\pos(662,330)}A{\fscx0}B{\fsc}C
Dialogue: 0,0:00:00.02,0:00:05.02,Default,,0,0,0,,{\an5\pos(662,400)}ABC
Dialogue: 0,0:00:00.02,0:00:05.02,Default,,0,0,0,,{\an5\pos(662,470)}A{\fscx-10}B{\fsc}C
```
vsfilter:
![unknown-15](https://user-images.githubusercontent.com/819638/93551699-26099800-f934-11ea-97f2-b3a0f2894a97.png)

libass:
![image](https://user-images.githubusercontent.com/819638/93551709-30c42d00-f934-11ea-8934-7bb95be2ef6e.png)

Oddly, we seem to _layout_ the rest of the line correctly (the positioning's right even with `\an5`), the characters are just… blank.

**Comment by astiob** [comment] 2020-09-18 13:09
This is a duplicate of #185 and #413.

**Closed** 2021-04-29 00:15 UTC
Labels: bug, compatibility
