### ISSUE TITLE
Script resolution questions

### ISSUE THREAD

**Issue by xwlcn** [libass/libass#478] opened 2021-02-24 11:55 UTC
subtitle content:
```
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: sub
Original Script: FIXSubtitleGroup
Synch Point: 1
ScriptType: v4.00+
WrapStyle: 2
Timer: 100.0000
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: no

[Aegisub Project Garbage]
Last Style Storage: Default
Video File: ?dummy:23.976000:36000000:1920:1080:25:101:87:
Video AR Value: 1.777778
Video Zoom Percent: 0.718750
Active Line: 9
Video Position: 1078

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,华文黑体,15,&H00FFFFFF,&H00000000,&H00FFFFFF,&H80000000,-1,0,0,0,100,100,0,0,1,0.1,0.4,8,10,10,20,1
Style: 特效,微软雅黑,20,&H00FFFFFF,&HFF0000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,2,10,10,10,1
Style: 注释,微软雅黑,18,&H00DEDEDE,&HFF000000,&H00000000,&H00000000,0,0,0,0,99.9998,100,0,0,1,1.5,0,8,0,0,5,1
Style: 歌词,微软雅黑,13,&H00DEDEDE,&H00000000,&H00000000,&H00000000,0,0,0,0,99.9998,100,0,0,1,1,0,7,15,5,20,1
Style: 特效 - 背景,微软雅黑,20,&H00FFFFFF,&HFF0000FF,&H00000000,&H00000000,0,0,0,0,99.9998,100,0,0,3,1,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\pos(12,26.5)\a4\p1\fscx30\fscy40\c&H392810&}m 0 0 l 250 0 l 250 344 l 0 344 l 0 0
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\pos(12,26.5)\a4\p1\fscx30\fscy40\c&HC6C772&}m 0 41 l 65 41 l 65 111 l 0 111 l 0 41
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\pos(12,26.5)\a4\p1\fscx30\fscy40\c&H5E4E11&}m 65 41 l 250 41 l 250 111 l 65 111 l 65 41
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\pos(12,26.5)\a4\p1\fscx30\fscy40\c&HCED6C7&}m 0 111 l 250 111 l 250 301 l 0 301 l 0 111
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\pos(12,26.5)\a4\p1\fscx30\fscy40\c&HD2D6D1&}m 6 123 l 108 123 l 108 263 l 6 263 l 6 123
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\pos(12,26.5)\a4\p1\fscx30\fscy40\c&H82791E&\1a&H8D&}m 6 248 b 14 243 23 238 33 234 l 30 205 l 28 200 b 25 199 25 197 25 193 b 23 190 24 186 24 183 b 24 182 24 180 25 179 b 25 177 22 174 23 172 b 24 170 25 171 26 173 b 26 165 27 156 30 151 b 33 141 42 132 57 129 b 77 129 85 138 89 153 b 91 159 92 166 92 172 b 94 172 94 174 94 176 b 93 178 92 180 92 182 b 93 185 93 189 93 193 b 91 197 91 200 89 201 b 88 209 86 215 83 221 b 83 227 82 235 86 236 b 93 237 101 239 108 242 l 108 263 l 6 263 l 6 248
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\fn华文中宋\b1\fs16\pos(58.971,65)\fsp1\c&HCED6C7&}卢浮{\fsp0}宫
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\a5\fn方正兰亭准黑_GBK\\fs7\c&H5F500F&\pos(47.2,75)}室内维护{\fs4}\N\N{\fs7}及保洁\N\N\N清洁工\N\N\N\N\N\NLVR716-ACC
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\a3\fn方正兰亭准黑_GBK\\fs7\c&H5F500F&\pos(84.5,145)}有效证件\N{\b0\fn方正兰亭中黑_GBK}31/12/2020
Dialogue: 0,0:00:44.94,0:00:48.42,特效,,0,0,0,,{\a1\fn方正兰亭准黑_GBK\fs10\c&H5F500F&\pos(14,145)}路易·佩雷纳
```
PlayResX: 384
PlayResY: 288
When the video resolution is 1920x1080, Use the following command to encode the video:
> ffmpeg -i 1920_1080_video.mkv -vf ass=sub.ass test.mp4

but the drawing is wrong：
![微信截图_20210224194200](https://user-images.githubusercontent.com/15356897/108995807-93d2a080-76d8-11eb-872a-dd444ae5f0f0.png)

If I use VSFilter, drawing is correct:
![微信截图_20210224194632](https://user-images.githubusercontent.com/15356897/108996157-05125380-76d9-11eb-9043-17f075f3b807.png)

and use PotPlayer load subtitle is the same result with VSFilter.

So, Is this a bug or is there something wrong with my command?

I tried to use the following command to specify resolution:
> ffmpeg -i 1920_1080_video.mkv -vf ass=sub.ass:original_size=384x288 test.mp4

Although the background graphics are correct, the text is stretched horizontally. So I had to change the scaleX of the script from 100 to 75 to display it correctly.

Can someone help me explain why this is caused? :)

**Comment by xwlcn** [comment] 2021-02-24 14:34
I found that when I reset the script resolution with aegisub, when ScaleX/Y is 100%, the correct way should be to keep unchanged, but resetting the script resolution will change ScaleX/Y, resulting in text deformation.

**Comment by TheOneric** [comment] 2021-02-24 14:38
> ScaledBorderAndShadow: no

What libass version are you using? There were some changes to SBAS=no scaling a while back (d60f2dce1dcafaed0e21406213e66072f3036752, though this is only relevant when storage size was not set by the API-user).

> So I had to change the scaleX of the script from 100 to 75 to display it correctly.

This part is a known bug in current libass, we scale most things with vertical ratio, but VSFilter uses more see https://github.com/libass/libass/issues/171#issuecomment-629902664.

I see the fonts in those two screenshots are different as well. Were they taken on different setups with different fonts available or is this another libass-issue?


Generally speaking for new subs, I'd recommend to both set SBAS=yes and use a Script Resolution of same ratio as the actual video. This not only works around incompatibilities but also avoids some unintuitive behaviour. *(Eg eventhough both \bordx and \bordy are set to the same value, they can end up with a different pixel-width when resolution ratio mismatches in VSFilter and soon™ also in libass)*

**Comment by xwlcn** [comment] 2021-02-24 14:58
Thank you for your reply.
The font in the picture above has no effect. The main problem is the background drawing behind the text. Obviously, when original_size is not specify, the background width is wrong, but when using original_ size, although the background width becomes normal, the whole subtitle text is stretched horizontally:
![微信截图_20210224225430](https://user-images.githubusercontent.com/15356897/109018870-6e06c500-76f3-11eb-89e2-d8cee5fd77e9.png)

**Comment by TheOneric** [comment] 2021-02-24 17:08
> The main problem is the background drawing behind the text.

Until #171 is fixed, your only (non-hacky) option is to resample the script to use a matching `PlayRes{X,Y}`.

> libass-version: 20200714-66dba8d

This commit predates the aforementioned change. As ffmpeg does _not_ set storage size, upgrading libass might affect some things, but it does **not** fix #171.

> when setting `original_size=384x288`

That's an ffmpeg filter option, not directly a libass option. I'd need to look into it to say for sure, but I wouldn't be surprised if text being stretched is the intended behaviour.

If you think the `original_size` thing is due to an libass bug or there's something else I missed, feel free to reopen. Currently this issue seems like a duplicate of #171 to me.

**Comment by TheOneric** [comment] 2021-02-24 17:11
> I found VLC, mpv all have this problem, but PotPlayer is no problem.

Does PotPlayer use libass?

**Comment by xwlcn** [comment] 2021-02-24 17:39
> > I found VLC, mpv all have this problem, but PotPlayer is no problem.
> 
> Does PotPlayer use libass?

I don't think it use libass, but I'm not soure, I found `AviSynth` folder in its install location.

**Comment by TheOneric** [comment] 2021-02-24 18:11
> I don't think it use libass

Ok thanks, than this is indeed a duplicate of #171.

**Closed by TheOneric** 2021-02-24 18:11 UTC
Labels: compatibility, duplicate

**Comment by xwlcn** [comment] 2021-02-25 06:18
@TheOneric 
Hello, I checked the source code implementation today, and it seems that I have found the problem. I have made the following modifications to `ass_render.c` , which can render correctly. In function `parse_events`, line 1992:
```
double dar = ((double) render_priv->orig_width) / render_priv->orig_height;
double sar = ((double) render_priv->track->PlayResX) / render_priv->track->PlayResY;
double par = dar / sar;
//only if render_priv->state.scale_x != 1 then scale it, otherwise text will be stretched.
info->scale_x = render_priv->state.scale_x * ( render_priv->state.scale_x != 1. ? par : 1.); 
```
but I don't know if it will cause other bugs.
