### ISSUE TITLE
libass no longer changes base direction based on encoding

### ISSUE THREAD

**Issue by lirbar** [libass/libass#295] opened 2018-01-01 22:04 UTC
I was referred here from VLC (VideoLAN) [forums](https://forum.videolan.org/viewtopic.php?f=12&t=141606)

It seems libass doesn't respect ASS Encoding flag. I specifically testing Hebrew subtitles with latest nightly VLC (3.0.0 rc2) on latest macOS 10.13.2 - which have the following issue. While previous VLC versions 2.2.8 doesn't (probably since it used older libass version).

Hebrew is written from right to left, so even when VLC knows that the subtitle is in Hebrew (track's language) and ASS Encoding flag is set to 177 - it's still shows LTR punctuations which means that " . ? ! , " shows in the beginning and not in the end of the sentence.
This means that the punctuations shown in the wrong direction - like English (ASS encoding flag = 0).

Here is the info about ASS Styles Encoding flag:
https://en.wikipedia.org/wiki/SubStation_Alpha
Encoding. Useful for writing other alphabet characters in ASCII. With Latin characters, this is set to zero. With Japanese characters, it can be set to 128 (ex: ‹ó displays Sora kanji). With Hebrew characters, it can be set to 177.

As said, the issue doesn't exist (ASS encoding flag 177 leads to RTL punctuations and flag 0 leads to LTR - as it should be) on VLC 2.2.8 in the same macOS system.

**Comment by anoosi** [comment] 2018-01-02 01:34
use -1 flag and libass will detect the direction automatically

**Comment by lirbar** [comment] 2018-01-02 09:31
Thanks that works nicely, but what with older ASS files that have the flag set with the old 177 flag ?
Is it a lot of work to support also the 177 flag, as was in the past ?

**Comment by anoosi** [comment] 2018-01-02 09:54
the same with me :(
i use arabic language, it's flag was 178 rtl also
but this option change from 0.13.3 version you can see the changelog
https://github.com/libass/libass/blob/master/libass/ass_shaper.c
see the comment in the last

**Comment by lirbar** [comment] 2018-01-02 09:59
Oh, I see. Anyone from the dev team can help us fix both Hebrew and Arabic by updating the code to the following ?

/**
 * \brief Resolve a Windows font charset number to a suitable base
 * direction. Generally, use LTR for compatibility with VSFilter. The
 * special value -1, which is not a legal Windows font charset number,
 * can be used for autodetection.
 * \param enc Windows font encoding
 */
FriBidiParType resolve_base_direction(int enc)
{
    switch (enc) {
        case -1:
            return FRIBIDI_PAR_ON;
        case 177:
            return FRIBIDI_PAR_ON;
        case 178:
            return FRIBIDI_PAR_ON;
        default:
            return FRIBIDI_PAR_LTR;
    }
}

**Comment by wm4** [comment] 2018-01-02 14:36
From what it looks like, this was done because VSFilter does it this way. This is needed for compatibility with old scripts.

**Comment by lirbar** [comment] 2018-01-02 15:29
> From what it looks like, this was done because VSFilter does it this way. This is needed for compatibility with old scripts.

Yes, but my small addition in bold above will keep the VSFilter compatibility while still support all previous Arabic and Hebrew ASS files. Do you see an issue with doing my suggested fix ?

**Comment by wm4** [comment] 2018-01-02 15:35
Well I thought the commit you pointed out explicitly removed those, stating compatibility as a reason. I haven't looked too closely at it, but it looks to me like your changes would break vsfilter compatibility again.

**Comment by wm4** [comment] 2018-01-02 15:35
CC @grigorig

**Comment by lirbar** [comment] 2018-01-02 15:48
> but it looks to me like your changes would break vsfilter compatibility again.
Yeah, now that I looked more closely - it does seem like that :)
VSFilter is Windows-only. So the question is why do Linux, Mac and non-VSFilter Windows users should encounter this major issue with Hebrew/Arabic only for VSFilter compatibility ?
Maybe it's possible to enable this VSFilter compatibility only for VSFilter users ? or at least only for Windows users ?
Meaning to remove the 3 lines in @grigorig [commit](https://github.com/libass/libass/commit/c93cb3dbfb7357179379ffd19ff973cf062e2129#diff-88b8b5ba7fa04b02b453c70be0fbcf73) only for VSFilter / Windows users...

**Comment by wm4** [comment] 2018-01-02 15:57
> So the question is why do Linux, Mac and non-VSFilter Windows users should encounter this major issue with Hebrew/Arabic only for VSFilter compatibility ?

Because VSFilter "defines" the format, and is (or used to be) the most common software used to render ASS subtitles. At least in the past, subtitles were created mainly for VSFilter.

> Maybe it's possible to enable this VSFilter compatibility only for VSFilter users ? or at least only for Windows users ?

It might be possible to use `ass_set_style_overrides` to force the Encoding field to a value that forces the wanted direction.

**Comment by grigorig** [comment] 2018-01-02 16:07
VSFilter always assumes a left-to-right base direction, no matter what font encoding is used. At least that is what my observations show consistently. So using the font encoding as a base direction hint is problematic for compatibility and it was therefore removed. I'm sorry if you relied on this hack. It was a mistake to add base direction detection based on font encoding.

ASS/SSA compatibility is a minefield. Lack of proper standards means that the only reasonable choice seems to be to sticking to whatever VSFilter is doing.

As an alternative, consider using the explicit direction overrides that Unicode provides at the start of a line.

**Comment by wm4** [comment] 2018-01-02 16:12
> As an alternative, consider using the explicit direction overrides that Unicode provides at the start of a line.

I think this is about old files, possibly even muxed into mkv. So that's not so easy.

**Comment by lirbar** [comment] 2018-01-02 16:24
>muxed into mkv 

> 
Indeed that is the case.
We are discussing here to about all Arabic and Hebrew ASS files ever created (at least until now). VLC 2.2.8 is still the official download and AFAIK, the most popular video player.
I don't see why base direction detection based on font encoding is a mistake ? since there isn't a better way to declare this to the player and anyway this still shows on Wikipedia as the ASS way to set RTL or LTR.
If VSFilter doesn't have RTL support - it means that libass should drop support that worked fine so far ?

**Comment by lirbar** [comment] 2018-01-02 16:29
Oh and another thing, my code suggestion just set FRIBIDI_PAR_ON for Hebrew / Arabic. Which means DirectiOn-Neutral. This may work fine with VSFilter. I don't use VSFilter and can't test...

**Comment by astiob** [comment] 2018-01-02 22:33
**In short:** There are other right-to-left subtitle files that your change breaks instead. There’s no way of correctly rendering all subtitle files, but we try to correctly render the most of them. To create a right-to-left subtitle file that renders correctly in libass and VSFilter, use Unicode RTL embedding and wrap any ASS override tags in PDF + LTR mark + RTL embed.

> We are discussing here about all Arabic and Hebrew ASS files ever created (at least until now).

Unfortunately, no. As you’ll see from issue #224 and others, far from all Arabic and Hebrew ASS files are created for VLC.

> VLC 2.2.8 is still the official download and AFAIK, the most popular video player.

I can’t vouch for Arabic and Hebrew subtitles because I don’t watch any subtitles in those languages (or speak them), but in my experience with English subtitles, VSFilter is and always has been the main ASS renderer for which the majority of ASS files are created. VLC may be the most popular video player in general, but ASS files tend to be created for VSFilter and VSFilter-based setups tend to be recommended for viewing them.

But even if we assume VLC is in fact the common standard nowadays, remember that there were many years when libass didn’t even exist or had poor support for ASS or for right-to-left scripts. All Arabic and Hebrew ASS files older than that are necessarily designed for VSFilter and rely on its horrible treatment of right-to-left languages. By making the treatment of RTL languages more obvious in libass, we would (and did) actually end up breaking all _those_ files, which we want to avoid.

As a matter of fact, there have indeed been reports of Arabic files not working as intended with libass, which you can find on this issue tracker and on the [old one](https://code.google.com/archive/p/libass/issues). Indeed, one such report (#224) is exactly what led to the change you’re proposing to undo.

Basically, it comes down to: do we want to break all files created before libass became usable for right-to-left subtitles, as well as all files created after that targeting Windows and VSFilter, as well as ensure that all files created targeting libass now and in the future will display incorrectly in VSFilter; or do we want to handle all those files correctly and ensure compatibility with VSFilter for new files, but instead break those files that were created for libass between 2011 or later and 2016? I think the latter sounds like it breaks less, which is preferable. It is very unfortunate that it has come to a situation where we inevitably break something, but it would be wise to minimize the breakage.

> Maybe it's possible to enable this VSFilter compatibility only for VSFilter users ? or at least only for Windows users ?

We can’t switch the base direction just for Windows users, because the correct direction depends on the file; it depends on what the author of the subtitles used, not what the viewer uses. We also can’t switch it just for files designed for VSFilter, because we don’t know whether a file is designed for VSFilter or not.

> since there isn't a better way to declare this to the player and anyway this still shows on Wikipedia as the ASS way to set RTL or LTR.

There is another way, but it needs to be done on each Dialogue line rather than in the Style line. Note that Wikipedia doesn’t actually say that the Encoding field affects text direction. It simply says it’s suited for Hebrew characters, but this is only to ensure that the right characters are displayed when non-Unicode fonts are used.

If a subtitle author wants to use standard right-to-left ordering, they should insert a Unicode right-to-left embedding character (U+202B) at the start of the line, after any ASS override tags (`{\things}`). If there are no override tags in the middle of the line, this is enough.

If there are, then, at the moment, even more work needs to be done to ensure full compatibility between libass and VSFilter, so that the subtitles look the same in all players. This may or may not change in future libass versions, but if it does, then libass will start behaving like VSFilter, so I personally wouldn’t recommend relying on libass’s current behaviour. The thing is: VSFilter splits the line on override tags, renders each section separately and orders the sections left-to-right, even if you have an RTL override at the start. On the other hand, libass currently applies directional control characters to the whole line at once. To get libass to order the sections left-to-right like VSFilter and to get VSFilter to order text including punctuation right-to-left within each section, insert a right-to-left embedding character (U+202B) immediately after each override tag and insert the two characters “pop directional formatting” (U+202C) and then “left-to-right mark” (U+200E) immediately before each override tag. (Alternatively, the left-to-right mark can be after the override tag. It doesn’t matter; it just needs to be between the U+202B and the U+202C.) Of course, since the sections are ordered left-to-right, you need to manually reorder parts of the sentence. This is tedious, but it’s the only way that lets you use override tags in right-to-left languages in VSFilter.

> If VSFilter doesn't have RTL support - it means that libass should drop support that worked fine so far ?

VSFilter does have some RTL support, but it’s obviously incomplete. Like I said above, it essentially splits the line on override tags and applies the bidirectional algorithm within each section, but it always orders the sections left-to-right and it always assumes a left-to-right base direction, which affects neutral characters such as punctuation at the edges of the line.

Note that if an override tag doesn’t actually change any parameter, then it does not split the line.

**Comment by astiob** [comment] 2018-01-02 22:43
@grigorig Why do we still have `Encoding=-1` autodetect base direction? VSFilter doesn’t do that either. Is this intentional?

**Comment by anoosi** [comment] 2018-01-03 21:29
@astiob whatever,
this problem should fixed in libass and vsfilter,
i just can not imagine why RTL languages are not supported!
is it possible that in order for me to write in arabic, i must put Unicode in every line?
anyway, i am grateful for your efforts, but we are asking for more serious attention, thanks

@lirbar i made a lua script [ageisub] to add rtl to the lines by adding <U+202B> to the lines
https://github.com/anoosi/Arabic-RTL-Karaoke-Template-Aegisub/blob/master/add-rtl.lua
you can use it

**Comment by SafaAlfulaij** [comment] 2018-01-06 16:57
@anoosi It's okay, it is hard for the team to actually get another behaviour with everything fixed, with a tag or so, a change in the ASS file header, 4.1, 4.x, 4.rtl, anything. They just have to stick to one code base and ruin everything. They also try to make things that are actually working somehow great (#221), to be useless.

It's either 5.0 or nothing. Just stop fansubbing, or move to srt :-)
And if you are a fanwatcher, then just stop watching. There are lots of other enjoyable stuff in this world, why sticking to this library?

**Comment by astiob** [comment] 2018-01-08 18:41
Let’s make one thing clear: libass is an ASS renderer. The main job of libass is to render ASS subtitles the same way other renderers do, have done and will do. This includes ASS files that were designed in 2004, in 2007, in 2013 and in 2020, and written in English, Arabic, Chinese or Mongolian.

@anoosi As it stands, you’re asking us to change the behaviour of ASS subtitles in a way that breaks existing files and compatibility with other renderers. For another perspective, consider that Web browsers even nowadays contain a special mode that renders pages similar to the way Internet Explorer 5 (released 18 years ago!) rendered them. If Web browsers suddenly decided to render those same pages in more modern ways, a lot of old (and not so old) Web sites would appear quite broken, although I guess not quite as broken as right-to-left text is in ASS. They retain this mode so that you can open any old Web site and see it like it was meant to be seen, and we try to do the same in libass. But it is possible to change the format in the future, like we got HTML 5, so please read on.

It’s easy to say that VSFilter should properly support right-to-left scripts, but it seems nearly impossible to implement in VSFilter, especially (again) without breaking old ASS files. However, it may be possible to implement it partly, so perhaps we should start a discussion with current maintainers of the living VSFilter branches on this. In any case, this change cannot affect existing files, because many existing files depend on VSFilter’s current behaviour and reorder the text in such a way that it displays correctly in VSFilter. To preserve compatibility with those files, the new, standard—or at least mostly standard—bidirectional rendering would need to be opt-in, using a new ASS header or override tag.

@SafaAlfulaij We (libass developers, or at least some of us) aren’t opposed to introducing a new header or override tag to denote proper right-to-left handling. I don’t know where you got this impression from. Some other people in this area have historically opposed new extensions of the ASS format, but I can’t say what their position is now.

(Note that if it’s an override tag, then from a certain perspective it’s not significantly better than the U+202B character that works already, as it has to go in each line. It would at least be visible though, and maybe it could somehow be made better.)

#221, as far as I understand, shows something working in VSFilter and not working in libass—which means we treat it as a bug and want to fix it so that it works in libass the same way it currently works in VSFilter. It’s the exact same position that we hold on the issue we’re currently discussing, namely #295: we replicate VSFilter’s behaviour. VSFilter always lays out text left-to-right—so we do the same. You seem to insinuate that we intentionally broke the fill in #221, which is not true at all.

The problem with unilaterally introducing an incompatible change, even if it’s opt-in, is that libass would be the only renderer supporting it. This is undesirable for many reasons, but the clearest reason is that many people watch video with subtitles on Windows using VSFilter and not libass. If you started producing subtitles that work only in libass, your viewers would have to switch to different software to see them. Historically this meant switching to another media player entirely, which may be very painful for the viewer, but I think there was some renewed effort to make a libass DirectShow filter recently, which would make it work wherever VSFilter works (mostly).

Also worth keeping in mind is that if we were to hide the new behaviour behind a header or override tag, then VSFilter would still open the new files but render them incorrectly, confusing the user; and if we were to make a whole new file format (ASS 5 or whatever), then VSFilter users would not see subtitles at all. It’s not immediately clear which option is better.

The best scenario would be if we could patch VSFilter itself to better support right-to-left writing (and possibly correct other historical bugs and inconsistencies while we are at it). This could be enabled by a new header or a new format, it doesn’t matter much, but users would still need to update their VSFilter or see broken subtitles (or none at all). An important thing to realize here, though, is that while RTL support could quite possibly be _improved_ in VSFilter, it seems nigh impossible to add full support for the Unicode bidirectional algorithm across override tags. I’d love to be wrong about this, though.

**In any case, this issue is well worth discussing, but libass simply switching to RTL base direction as-is is not the solution.** And whatever solution we may end up with will most likely take some time to be agreed on and implemented. So please bear with us, feel free to suggest your ideas _keeping in mind backwards-compatibility_ and stick to VSFilter’s mostly-left-to-right world for the time being. I know it must hurt having to resort to ugly hacks to make your language look right while English works out of the box, but it’s the best we’ve got at the moment and we should convert the frustration into effort to improve the future.

> Just stop fansubbing, or move to srt :-)

I’m afraid SRT won’t help you much—many media players render SRT via libass or VSFilter anyway. Not to say that this is good, because of issues like this.

> And if you are a fanwatcher, then just stop watching. There are lots of other enjoyable stuff in this world, why sticking to this library?

I’m not sure how stopping watching helps anybody or what it has to do with libass.

**Comment by wm4** [comment] 2018-01-08 19:39
Let's just get this out of the way: _is_ VSFilter still maintained?

> @SafaAlfulaij We (libass developers, or at least some of us) aren’t opposed to introducing a new header or override tag to denote proper right-to-left handling.

There's even a solution which I mentioned (style overrides, would have to be exposed by client applications like vlc - at least mpv does).

**Comment by astiob** [comment] 2018-01-08 19:48
> Let's just get this out of the way: is VSFilter still maintained?

MPC-HC’s—yes. Well, at least it was maintained when I last checked. They did a lot of work improving its performance, cleaning up the code and even attempting some bug fixes.

xy-VSFilter—not so much. It’s not actively developed, but I have faith that @Cyberbeing may accept pull requests and make a new release if we ask him.

**Comment by astiob** [comment] 2018-01-08 19:51
But overall it does seem quite hard to actually achieve change in VSFilter and have it propagate across the install base. Which is one more reason to avoid making unilateral changes in the format that break rendering in VSFilter.

**Comment by Cyberbeing** [comment] 2018-01-09 09:27
Yes, if there was a pull request for something, I'd compile and release a new build. Otherwise xy-VSFilter project is considered dead, since it's lacked a developer for a very long time now.

**Comment by anoosi** [comment] 2018-01-09 09:54
@astiob I understand what you mentioned before, but the issue of adding support for right-to-left languages is not so complicated, we can simply add in the header file under [Script Info] like 

> [Script Info]
> base_direction: rtl

this option it would be good if add also in xy-VSFilter , VSFilter
and the mode of action will be like Unicode <U+202B>.
in this case the old files will not be affected by this change because they do not have in header base_direction: rtl

man, if you do not try to take this step, who will do it?
for me @SafaAlfulaij he is right, for years from now, you have been receiving feedback from arab users and have not taken a positive step towards us!
at the last, i can only reiterate my gratitude for your efforts to make this library more suitable for users to rely on..

**Comment by realfinder** [comment] 2021-03-08 19:37
well, https://github.com/libass/libass/issues/224 is why this changed, so this issue (295) should be closed, I think? I see no problem for using -1 Encoding as a neutral and satisfactory solution for all

**Comment by TheOneric** [comment] 2021-12-27 22:54
The change for all legal codepage values was done for VSFilter compatibility and like other emulated VSFilter-quirks will not be reverted for the sake of compatibility with existing old subtitles and currently used VSFilter builds.  
At the same time, we do acknowledge that VSFilter(-compatible behaviour) is especially problematic for LTR and complex-shaping users, which is why there's the libass-specific `Encoding:-1` extension, which changes the default text direction to auto and btw will also enable some other VSFilter-incompatible changes beneficial for users of LTR or complex shaping, see #441.

**Closed by TheOneric** 2021-12-27 22:54 UTC
