### ISSUE TITLE
VSFilter Borderstyle=3 shenanigans

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#396] opened 2020-05-18 01:45 UTC
*VSFilter seems to shift text in strange ways, depening on the Outline value, when Borderstyle=3 is involved
Libass currently keeps the text position unchanged.
In case of Borderstyle=1 both keep the text position constant.

For a 1px difference see `bordx-coll2.ass` from #395 .  For a more visible shift see `frame-edge_bs3.ass` (video also at linked pr):
```
﻿[Script Info]
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 640
PlayResY: 480
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: DefaultB,DejaVu Sans,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,3,30,0,2,5,5,5,1
Style: DefaultR,DejaVu Sans,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,3,5,0,2,5,5,5,1
Style: DefaultS,DejaVu Sans,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,3,1,0,2,5,5,5,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Comment:  0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,Margin{L,R,V} of style are 5; Outline=30
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an8}NNNN
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an9}NNOO
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an6}OOOO
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an3}SSOO
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an2}SSSS
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an1}SSWW
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an4}WWWW
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an7}NNWW
Dialogue: 0,0:00:00.00,0:00:05.00,DefaultB,,0,0,0,,{\an5}××××
Comment:  0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,Margin{L,R,V} of style are 5; Outline=5
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an8}NNNN
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an9}NNOO
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an6}OOOO
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an3}SSOO
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an2}SSSS
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an1}SSWW
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an4}WWWW
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an7}NNWW
Dialogue: 0,0:00:10.00,0:00:15.00,DefaultR,,0,0,0,,{\an5}××××
Comment:  0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,Margin{L,R,V} of style are 5; Outline=1
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an8}NNNN
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an9}NNOO
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an6}OOOO
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an3}SSOO
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an2}SSSS
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an1}SSWW
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an4}WWWW
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an7}NNWW
Dialogue: 0,0:00:20.00,0:00:25.00,DefaultS,,0,0,0,,{\an5}××××
```

**xy-VSFilter:**
![grafik](https://user-images.githubusercontent.com/1668471/82165435-4c032b00-98b5-11ea-8113-6628dff47bbd.png)
![grafik](https://user-images.githubusercontent.com/1668471/82165458-69d09000-98b5-11ea-9085-c5ec919809a3.png)
![grafik](https://user-images.githubusercontent.com/1668471/82165480-8076e700-98b5-11ea-8ce0-f54a5f13884e.png)

*(Note that `××××` isn't even always in the center of the border-box and that this is not related to margin,border,frameedge collsions as it also affects the \an line and other cases)*

**libass:**
Libass behaves more intuitively and doesn't change the text position. Note that if Bordstyle=1 xy-VSFilter does the same as libass.
![grafik](https://user-images.githubusercontent.com/1668471/82166510-f2046480-98b8-11ea-938a-b4dec35600fd.png)
![grafik](https://user-images.githubusercontent.com/1668471/82166521-fcbef980-98b8-11ea-944b-b31c2bd2ac4d.png)
![grafik](https://user-images.githubusercontent.com/1668471/82166526-021c4400-98b9-11ea-9fdf-1fc9061161fa.png)

<br /><br />

Though I'm generally in favour of compatibility, I'm not convinced it is actually a good idea to replicate this behaviour in libass. It is unintuitive – worse: I can't see any predictable pattern one might get used to – and it will probably look horrible with `\t`.
Under these conditions I also doubt that Borderstyle=3 and border-values exhibiting this behaviour were widely used for accurate typesetting with VSFilter (instead of draw).
libass' sane Borderstyle=3 on the other hand might have been sufficient for this and hypothetical typesets using libass' Borderstyle=3 might break.
I don't think I have any example either way though, were Borderstyle=3 was used and exact positioning was important, so that's just an guess.

Well, that being said, my opinion on this is irrelevant.  If this will be emulated by libass I'll just have to pass on using Borderstyle=3 in the future.

**Comment by astiob** [comment] 2020-05-18 01:59
Looks fine in MPC-HC, so this might be a rare xy-VSFilter rendering bug. I’ll test with guliverkli2 (the timeless classic xy-VSFilter and also/therefore libass aim to avoid breaking) later.

As for using this in subtitles, if different popular renderers show it significantly differently, IMO a responsible author shouldn’t be using it anyway, even if one renderer does it in a seemingly sane way.

**Comment by astiob** [comment] 2020-05-18 21:50
OK, you can relax. :-) In any case, thanks a lot for the initial investigation and the detailed report with samples and screenshots!

This is a regression in xy-VSFilter somewhere after version 3.0.0.8 and before or in version 3.0.0.41. I tried to bisect, but I get tons of compilation errors in VS2019 of which I’ve managed to fix several and have no idea about the rest, and I kinda don’t want to (re)install VS2010 (not least because I fear it will mess up my configuration and leave a mess even after subsequent uninstalling; I’m having flashbacks to when I still had multiple versions installed and decided to clean them up and upgrade…). Maybe I, or someone else, will have luck reading the code of the 33 commits.

cc @Cyberbeing
(By the way, have you nuked the xy-VSFilter GitHub issue tracker or was it never a thing?)

Since this is simultaneously “insane”, a regression from guliverkli2, and absent from MPC-HC, not even I want to emulate this. So I’m closing this issue.

guliverkli2 VSFilter 2.39.5.2 20090624 Unicode:
![guliverkli2 renders this in the “sane” way, the same as libass.](https://user-images.githubusercontent.com/515193/82262014-ce005c00-9968-11ea-8605-77f712b92e22.png)

xy-VSFilter 3.0.0.8:
![xy-VSFilter 3.0.0.8 renders this in the “sane” way, the same as libass.](https://user-images.githubusercontent.com/515193/82262376-7adad900-9969-11ea-9140-5080579f15ef.png)

xy-VSFilter 3.0.0.41:
![xy-VSFilter 3.0.0.41 renders this in the same way as current xy-VSFilter and XySubFilter.](https://user-images.githubusercontent.com/515193/82262493-a9f14a80-9969-11ea-8f72-3ca44d2079ab.png)

**Closed by astiob** 2020-05-18 21:50 UTC
Labels: compatibility

**Comment by Cyberbeing** [comment] 2020-05-19 05:20
On xy-VSFilter's side the issue seems to be caused by the following commit which added the OverlayNoOffsetKey cache: https://github.com/Cyberbeing/xy-VSFilter/commit/6e1e5c4f8066c3d9d691c8e76c5ebfd64fc84fbc

If you remove the DefaultB lines, it doesn't occur. 
If you change the contents of the text to not be identical for each set, it doesn't occur.
If you reverse the order of the lines DefaultS > DefaultR > DefaultB, the symptoms are even worse.

@astiob Any ideas of how to fix it?

After Google Code shut down, I may have never enabled Issues on Github, or maybe I disabled it a few years ago when the developer went missing, I can't remember now. In the future, feel free to use Pull Requests for issues and regressions like this which should be fixed.

**Comment by Cyberbeing** [comment] 2020-05-19 08:33
@astiob If I change https://github.com/Cyberbeing/xy-VSFilter/commit/6e1e5c4f8066c3d9d691c8e76c5ebfd64fc84fbc#diff-cbd5dbecc495743b2f9ef9388af4a7e7R305:

```
    if (m_style.get().borderStyle==1)
    {
        	border_x = border_y = 0;
    }
```

to

```
    if (m_style.get().borderStyle==1)
    {
    	if(!CreateOpaqueBox())
        {
        	border_x = border_y = 0;
        }
    }
```
it seems to avoid improper cache hits with that sample, but is doing this actually the proper fix? I don't really understand what this part of the code is trying to do, or if it would have unintended consequences elsewhere. I've attached builds based on xy-VSFilter 3.0.0.306 & xySubFilter 3.1.0.752 with the above change for testing.


[xy_test_issue396.zip](https://github.com/libass/libass/files/4649123/xy_test_issue396.zip)

**Comment by astiob** [comment] 2020-05-19 22:17
Thanks for tracking it down!

To be honest… I’ve been staring at the code for a while, and I don’t understand it completely either.

The overall intention is clear: to cache the result of running `Rasterizer::Rasterize` (via `CWord::PaintFromScanLineData2`). An obvious guess, then, is that the problem might be that the cache _key_ for this is missing some important information. Like the border style, for example. Or indeed the border width, which the original commit intentionally erases away but your hack-patch forces to be kept.

But what I don’t understand yet is what exactly `OverlayNoOffsetMruCache` is supposed to do beyond just looking up the `OverlayNoBlurMruCache` by `key`, or why `CreateOpaque` is called from here at all. I’ll explore some more tomorrow.

**Comment by Cyberbeing** [comment] 2020-05-20 06:45
>or why CreateOpaque is called from here at all

My main fear with the hack-patch is if indeed it's never called there, and always returns false. The same effect as removing `border_x = border_y = 0;` entirely.

Another observation with the above patch, is even though it misses OverlayNoOffsetMruCache it now hits the GetScanLineData cache instead. 

This suggests it ends up triggering the else statement here: https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/subtitles/RTS.cpp#L293

So the incompatibility with OpaqueBox likely exists here: https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/subtitles/RTS.cpp#L287-L288 particularly  `- ((wide_border+7)&~7)` . Something to do with VSFilter internally converting OpaqueBox to a polygon vector which calculates offsets differently?

If I revert the patch in https://github.com/libass/libass/issues/396#issuecomment-630671913 and instead delete  `- ((wide_border+7)&~7)` it also seems to resolve the bug with this sample. Though unlike the first patch, this change causes a different bug. Or rather the exact same bug I ran into when the developer initially implemented the OverlayNoOffset cache. Unfortunately the the YuvOptions2 branch he linked from the email on repo.or.cz was deleted, so the log of the fix is lost, but maybe this is what he actually changed.

**Comment by Cyberbeing** [comment] 2020-05-23 04:51
@astiob any further thoughts on how to make the implementation of the OverlayNoOffset cache fully compatible with the original VSFilter code & Libass?

Would it be correct to assume the if statement here https://github.com/Cyberbeing/xy-VSFilter/blob/59d9decce762a384c815000ecd74911fea1b82e7/src/subtitles/Rasterizer.cpp#L649 in the original code was never triggered for Opaque Box and a lack of an identical check in RTS.cpp after the cache was added may be causing the bug?

I did another test, reverted the https://github.com/libass/libass/issues/396#issuecomment-630671913 patch, and instead changed https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/subtitles/RTS.cpp#L283-L292

```
    if (pos)
    {
        SharedPtrOverlay raterize_result( DEBUG_NEW Overlay() );
        *raterize_result = *overlay_cache->GetAt(pos);
        raterize_result->mOffsetX = left_top.x - psub.x - ((wide_border+7)&~7);
        raterize_result->mOffsetY = left_top.y - psub.y - ((wide_border+7)&~7);
        PaintFromNoneBluredOverlay(raterize_result, key, overlay);
        result = true;
        overlay_cache->UpdateCache(key, raterize_result);
    }
```

to

```
    if (pos && !CreateOpaqueBox())
    {
        SharedPtrOverlay raterize_result( DEBUG_NEW Overlay() );
        *raterize_result = *overlay_cache->GetAt(pos);
        raterize_result->mOffsetX = left_top.x - psub.x - ((wide_border+7)&~7);
        raterize_result->mOffsetY = left_top.y - psub.y - ((wide_border+7)&~7);
        PaintFromNoneBluredOverlay(raterize_result, key, overlay);
        result = true;
        overlay_cache->UpdateCache(key, raterize_result);
    }
```
xy-VSFilter & XySubFilter Builds with the above change for testing: [xy_test_issue396v2.zip](https://github.com/libass/libass/files/4671152/xy_test_issue396v2.zip)

With that change, both OverlayNoOffset & GetScanLineData produce cache hits for the sample in the OP, and it doesn't seem to trigger the bugs in either that script or the aw_title script. So while the change in https://github.com/libass/libass/issues/396#issuecomment-630671913 broke the OverlayNoOffset cache for OpaqueBox, the above change doesn't, so maybe it's closer to being on the right track?

@astiob when a final solution to maintain compatibility is determined, can I leave it to you to create a pull request?

**Comment by astiob** [comment] 2022-11-04 20:18
@Cyberbeing Thanks for pushing that commit! I must admit that I still haven’t investigated it further :-( Let’s keep our fingers crossed for now!
