### ISSUE TITLE
build: no longer builds with ffmpeg past 18d6c07267994398f99b2241f577f8e7118af099

### ISSUE THREAD

**Issue by 1480c1** [libass/libass#654] opened 2022-10-19 18:57 UTC
### libass version

https://github.com/libass/libass/commit/75a3dbac9bd41842a4d00b0d42c9513e2c8aec67

### Is it a regression?

recent change since yesterday (see ffmpeg's commit)

### How did you invoke configure?

../configure --prefix=/local32 --enable-static --disable-shared

### System Information

Windows compiling using msys2 and mingw64 gcc

### Toolchain

gcc 12.2.0 from msys2

### Log of the error

copied from https://github.com/m-ab-s/media-autobuild_suite/issues/2305

```c
I:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: I:/MABS/local32/lib/libass.a(ass.o):ass.c:(.text+0x2ea0): multiple definition of `read_file'; fftools/ffmpeg_opt.o:ffmpeg_opt.c:(.text+0x2fb0): first defined here
```

### Additional info

read_file() added to ffmpeg at https://github.com/FFmpeg/FFmpeg/commit/18d6c07267994398f99b2241f577f8e7118af099

read_file() added to libass (the resulting library symbol) at https://github.com/libass/libass/commit/571185341f3e58bd57a823070dde30c66491a4ee

possible solution is to add a prefix to read_file from libass so it matches the rest of the function

**Comment by astiob** [comment] 2022-10-19 21:47
For reference, this happens to be a duplicate of #222, although the FFmpeg development is new.

**Comment by TheOneric** [comment] 2022-10-19 22:25
While it is indeed a good idea to rename `read_file` and other non-static generic internal functions in libass (as observed in #222), this alone doesn't really fix this problem. There are many existing libass releases with `read_file` which still won't be able to be linked statically to `ffmpeg` even if we rename the function in master. So you should definitely also contact ffmpeg to ensure the (now no longer static) `read_file` there is also renamed. I don't yet see a report about this in [their issue tracker](https://trac.ffmpeg.org/query?status=closed&status=new&status=open&status=reopened&col=id&col=summary&col=status&col=type&col=component&col=version&col=time&col=changetime&report=1&desc=1&order=time).

*(Also strictly speaking this is a ffmpeg regression not a libass one as libass had the function non-static for 7 years and ffmpeg only since yesterday)*.

**Comment by rcombs** [comment] 2022-10-19 23:31
Can we set up our static lib to be a relocatable-linked .o (perhaps archived as a single-file .a) rather than an actual .a archive of all our objects? That would deal with this kind of problem without needing to do anything annoying with our own internal hidden function names.

**Closed** 2022-10-24 15:39 UTC
Labels: build
