### ISSUE TITLE
0.15.1 breaks ffmpeg subtitle burning with utf-8 glyphs for osx

### ISSUE THREAD

**Issue by s22chan** [libass/libass#512] opened 2021-05-20 04:12 UTC
db85ef4736108c12bf3e12939447840815c246ec introduced an issue when trying to burn in non-english srts.

with:
```sh
ffmpeg -i "test.mkv" -vf subtitles='test.srt' -c:a copy -c:v h264_videotoolbox -b:v 8000k -map 0:v:0 -map 0:a:0 'out.mkv'
```
and:
```srt
1
00:00:03,125 --> 00:00:06,375
你好世界
```
results in:
```
[Parsed_subtitles_0 @ 0x7fc863206fc0] fontselect: (Arial, 400, 0) -> /System/Library/Fonts/Supplemental/Arial.ttf, -1, ArialMT
[Parsed_subtitles_0 @ 0x7fc863206fc0] Glyph 0x4F60 not found, selecting one more font for (Arial, 5, 400)
[Parsed_subtitles_0 @ 0x7fc863206fc0] fontselect: failed to find any fallback for font: (Arial, 400, 0)
[Parsed_subtitles_0 @ 0x7fc863206fc0] Glyph 0x597D not found, selecting one more font for (Arial, 5, 400)
...
```

when it's working, it should've done this:
```
[Parsed_subtitles_0 @ 0x7f99e8206380] fontselect: (Arial, 400, 0) -> /System/Library/Fonts/Supplemental/Arial.ttf, -1, ArialMT
[Parsed_subtitles_0 @ 0x7f99e8206380] Glyph 0x4F60 not found, selecting one more font for (Arial, 5, 400)
[Parsed_subtitles_0 @ 0x7f99e8206380] fontselect: (Arial, 400, 0) -> /System/Library/Fonts/PingFang.ttc, -1, PingFangSC-Regular
```

dev env instructions:
```sh
brew install ffmpeg
brew unlink libass
# make your debug build
ln -snf `pwd`/libass/.libs libass/lib
ln -snf `pwd`/libass /usr/local/opt
```

**Comment by astiob** [comment] 2021-05-20 12:42
I get:
```
[sub/ass] fontselect: (Arial, 400, 0) -> Helvetica, 0, Helvetica
[sub/ass] Glyph 0x4F60 not found, selecting one more font for (Arial, 5, 400)
[sub/ass] fontselect: (Arial, 400, 0) -> /System/Library/Fonts/ヒラギノ角ゴシック W3.ttc, -1, HiraginoSans-W3
```

Naming the specific font explicitly works, too:
```
[sub/ass] fontselect: (PingFangSC-Regular, 400, 0) -> /System/Library/Fonts/PingFang.ttc, -1, PingFangSC-Regular
```

**Comment by s22chan** [comment] 2021-05-20 13:52
maybe it's reliant on my brew dependencies? :/
```
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for freetype2 >= 9.10.3... yes
checking for fribidi >= 0.19.0... yes
checking for harfbuzz >= 1.2.3... yes
checking for fontconfig >= 2.10.92... yes
checking for CORETEXT... yes
checking for DIRECTWRITE... no
checking for nasm... no
```

**Comment by astiob** [comment] 2021-05-20 19:18
Just for a sanity check: are you sure you’re actually testing 0.15.1 and not by any chance 0.15.0? There was a Core Text regression in 0.15.0, but it was fixed in 0.15.1.

**Comment by TheOneric** [comment] 2021-05-20 19:39
If you're using 0.15.1, your logs will print a libass API and source version, if using 0.15.0 or earlier it won't.

**Comment by s22chan** [comment] 2021-05-20 21:22
I did a git bisect so it's definitely using the lib. What's in homebrew at the momemt is claimed to be 0.15.1.

**Comment by s22chan** [comment] 2021-05-20 23:01
for 2d2be32
```c
    CFNumberRef cfformat = CTFontCopyAttribute(fb, kCTFontFormatAttribute);
    CFStringRef cfname = is_postscript_font_format(cfformat) ?
        CTFontCopyPostScriptName(fb) : CTFontCopyFullName(fb);
```
`CTFontCopyFullName` is called and `cfname` is set to `PingFang SC Regular`

for db85ef4
`get_font_info_ct` finds `PingFangSC-Regular`, but the families returned has a localized name preferred (I'm on Big Sur 11.3.1)
```c
(char **) $21 = 0x0000000105a0f8a0
(lldb) p meta.families[0]
(char *) $22 = 0x0000000105a12770 "蘋方-簡"
(lldb) p meta.families[1]
(char *) $23 = 0x0000000105a1b7f0 "PingFang SC"
```

`蘋方-簡` fails to match any font in `find_font`, which returns `NULL`

**Comment by astiob** [comment] 2021-05-21 02:11
Very interesting. Thanks for the debugging!

Indeed, it fails to find the font for me if I request 蘋方-簡 (the traditional-characters name). But it does find it if I use 苹方-简 (the simplified-characters name). This happens even if my language preferences have Traditional Chinese before Simplified.

I can fully reproduce your report if I move Simplified Chinese above Japanese in my language preferences.

Curiously, if I move Traditional Chinese higher up, Core Text supplies PingFang TC as the fallback. That font, too, has traditional and simplified names, in the same order, but this time Core Text only finds it by the traditional name and fails lookup by the simplified name, again regardless of my language preferences.

I’ve also _just_ noticed that the commit you mentioned in the original report is the 0.15.1 regression fix commit; and yet I asked you to check that you weren’t seeing the regression that it was supposed to have fixed. Whoops.

Welp. Looks like Core Text’s `CTFontCollectionCreateMatchingFontDescriptors` honours at most one “unlocalized” and one “localized” name for each font. I’ve spent the night digging, but I’ll dig some more.

**Closed** 2021-06-07 11:42 UTC
Labels: fonts, macos, regression

**Comment by Turing-Chu** [comment] 2021-06-18 02:06
the following is error output, some duplicate messages are removed.

```bash
$ ffmpeg -i a.mp4 -vf ass=a.ass -y b.mp4
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'a.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:00:47.62, start: 0.000000, bitrate: 212 kb/s
  Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt470bg/unknown/unknown), 1920x1080 [SAR 120:71 DAR 640:213], 134 kb/s, 15 fps, 15 tbr, 15360 tbn, 30 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 74 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[Parsed_ass_0 @ 0x7ffe7bd4bd40] libass API version: 0x1501000
[Parsed_ass_0 @ 0x7ffe7bd4bd40] libass source: tarball: 0.15.1
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 2.8.1 (COMPLEX)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Using font provider coretext
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Added subtitle file: 'a.ass' (2 styles, 15 events)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: (Arial, 400, 0) -> /System/Library/Fonts/Supplemental/Arial.ttf, -1, ArialMT
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Glyph 0x88AB not found, selecting one more font for (Arial, 5, 400)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Glyph 0x4F20 not found, selecting one more font for (Arial, 5, 400)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
......
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Glyph 0x4EBF not found, selecting one more font for (Arial, 5, 400)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
[libx264 @ 0x7ffe7c022a00] using SAR=120/71
[libx264 @ 0x7ffe7c022a00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7ffe7c022a00] profile High, level 4.0, 4:2:0, 8-bit
[libx264 @ 0x7ffe7c022a00] 264 - core 161 r3049 55d517b - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=15 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'b.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    copyright       : 恒生电子股份有限公司
    encoder         : Lavf58.76.100
  Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt470bg/unknown/unknown, progressive), 1920x1080 [SAR 120:71 DAR 640:213], q=2-31, 15 fps, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 69 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc58.134.100 aac
frame=    1 fps=0.0 q=0.0 size=       0kB time=00:00:00.12 bitrate=   3.0kbits/s speed=3.0[Parsed_ass_0 @ 0x7ffe7bd4bd40] Glyph 0x88AB not found, selecting one more font for (Arial, 5, 400)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Glyph 0x4F20 not found, selecting one more font for (Arial, 5, 400)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
......
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] Glyph 0x4EBF not found, selecting one more font for (Arial, 5, 400)
[Parsed_ass_0 @ 0x7ffe7bd4bd40] fontselect: failed to find any fallback for font: (Arial, 400, 0)
frame=    4 fps=0.0 q=-1.0 Lsize=     133kB time=00:00:00.44 bitrate=2434.2kbits/s speed=0.592x    
video:126kB audio:6kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.209498%
[libx264 @ 0x7ffe7c022a00] frame I:1     Avg QP:20.13  size:125972
[libx264 @ 0x7ffe7c022a00] frame P:1     Avg QP:20.76  size:  1180
[libx264 @ 0x7ffe7c022a00] frame B:2     Avg QP:20.41  size:   568
[libx264 @ 0x7ffe7c022a00] consecutive B-frames: 25.0%  0.0% 75.0%  0.0%
[libx264 @ 0x7ffe7c022a00] mb I  I16..4: 20.0% 72.2%  7.8%
[libx264 @ 0x7ffe7c022a00] mb P  I16..4:  0.2%  0.0%  0.0%  P16..4:  6.5%  1.1%  0.1%  0.0%  0.0%    skip:92.0%
[libx264 @ 0x7ffe7c022a00] mb B  I16..4:  0.0%  0.0%  0.0%  B16..8:  5.5%  0.1%  0.0%  direct: 0.0%  skip:94.4%  L0:13.2% L1:86.8% BI: 0.0%
[libx264 @ 0x7ffe7c022a00] 8x8 transform intra:72.1% inter:100.0%
[libx264 @ 0x7ffe7c022a00] coded y,uvDC,uvAC intra: 62.1% 86.7% 51.2% inter: 0.1% 0.9% 0.0%
[libx264 @ 0x7ffe7c022a00] i16 v,h,dc,p:  6% 42%  5% 47%
[libx264 @ 0x7ffe7c022a00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 20% 13%  3%  7%  9%  5%  7%  6%
[libx264 @ 0x7ffe7c022a00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 40% 22% 11%  2%  8%  7%  3%  3%  2%
[libx264 @ 0x7ffe7c022a00] i8c dc,h,v,p: 42% 27% 22%  9%
[libx264 @ 0x7ffe7c022a00] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x7ffe7c022a00] kb/s:3848.64
[aac @ 0x7ffe7e017200] Qavg: 964.069
Exiting normally, received signal 2.
$ 
```


ffmpeg installed by homebrew:

```
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 12.0.5 (clang-1205.0.22.9)
  configuration: --prefix=/usr/local/apps/homebrew/Cellar/ffmpeg/4.4_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
```

libass installed by homebrew: 

```json
{
  "homebrew_version": "3.1.5-14-ga81a76b",
  "used_options": [

  ],
  "unused_options": [

  ],
  "built_as_bottle": true,
  "poured_from_bottle": true,
  "installed_as_dependency": false,
  "installed_on_request": true,
  "changed_files": [
    "lib/pkgconfig/libass.pc"
  ],
  "time": 1620468975,
  "source_modified_time": 1619919645,
  "compiler": "clang",
  "aliases": [

  ],
  "runtime_dependencies": [
    {
      "full_name": "libpng",
      "version": "1.6.37"
    },
    {
      "full_name": "freetype",
      "version": "2.10.4"
    },
    {
      "full_name": "fribidi",
      "version": "1.0.10"
    },
    {
      "full_name": "fontconfig",
      "version": "2.13.1"
    },
    {
      "full_name": "gettext",
      "version": "0.21"
    },
    {
      "full_name": "libffi",
      "version": "3.3"
    },
    {
      "full_name": "pcre",
      "version": "8.44"
    },
    {
      "full_name": "gdbm",
      "version": "1.19"
    },
    {
      "full_name": "mpdecimal",
      "version": "2.5.1"
    },
    {
      "full_name": "openssl@1.1",
      "version": "1.1.1k"
    },
    {
      "full_name": "readline",
      "version": "8.1"
    },
    {
      "full_name": "sqlite",
      "version": "3.35.5"
    },
    {
      "full_name": "xz",
      "version": "5.2.5"
    },
    {
      "full_name": "python@3.9",
      "version": "3.9.5"
    },
    {
      "full_name": "glib",
      "version": "2.68.1"
    },
    {
      "full_name": "pkg-config",
      "version": "0.29.2"
    },
    {
      "full_name": "libpthread-stubs",
      "version": "0.4"
    },
    {
      "full_name": "xorgproto",
      "version": "2021.4"
    },
    {
      "full_name": "libxau",
      "version": "1.0.9"
    },
    {
      "full_name": "libxdmcp",
      "version": "1.1.3"
    },
    {
      "full_name": "libxcb",
      "version": "1.14"
    },
    {
      "full_name": "libx11",
      "version": "1.7.0"
    },
    {
      "full_name": "libxext",
      "version": "1.3.4"
    },
    {
      "full_name": "libxrender",
      "version": "0.9.10"
    },
    {
      "full_name": "lzo",
      "version": "2.10"
    },
    {
      "full_name": "pixman",
      "version": "0.40.0"
    },
    {
      "full_name": "cairo",
      "version": "1.16.0"
    },
    {
      "full_name": "gobject-introspection",
      "version": "1.68.0"
    },
    {
      "full_name": "graphite2",
      "version": "1.3.14"
    },
    {
      "full_name": "icu4c",
      "version": "69.1"
    },
    {
      "full_name": "harfbuzz",
      "version": "2.8.1"
    }
  ],
  "source": {
    "spec": "stable",
    "versions": {
      "stable": "0.15.1",
      "head": null,
      "version_scheme": 0
    },
    "path": "/usr/local/apps/homebrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libass.rb",
    "tap_git_head": "1220c789207176204e85bb597fe56530da4f503c",
    "tap": "homebrew/core"
  },
  "arch": "x86_64",
  "built_on": {
    "os": "Macintosh",
    "os_version": "macOS 11.2",
    "cpu_family": "penryn",
    "xcode": "12.4",
    "clt": "12.4.0.0.1.1610135815"
  }
}
```

**Comment by TheOneric** [comment] 2021-06-18 11:17
@Turing-Chu This should have been fixed by 6fc9855, hence this issue was closed.
Your log suggests you're using the last release, which doesn't include this commit. Using git master should fix this, if not there would be another issue. *(afaik using git master is possible with `brew (re)install --HEAD libass`, but I'm not too familiar with brew and you might need to remove the HEAD version manually once a new stable gets released)*

**Comment by Turing-Chu** [comment] 2021-06-19 04:49
@TheOneric but your suggestion give me great help. I will recompile libass with the last release replacing which brew installed.

**Comment by umityilmazz** [comment] 2024-03-24 01:11
![image](https://github.com/libass/libass/assets/81180370/17046c76-e258-406a-900c-d06128b5672b)
I'm getting this error too and I couldn't solve it even though I tried hard. If you were able to solve this error, can you help me?

**Comment by astiob** [comment] 2024-03-24 16:20
What I see in the screenshot doesn’t seem like a clear error. Can you describe what kind of wrong behaviour you’re actually seeing?

**Comment by umityilmazz** [comment] 2024-03-27 06:20
> What I see in the screenshot doesn’t seem like a clear error. Can you describe what kind of wrong behaviour you’re actually seeing?`
I/flutter ( 3957): 30 fps, 
I/flutter ( 3957): 15360 tbn
I/flutter ( 3957): 
I/flutter ( 3957):     Metadata:
I/flutter ( 3957):       encoder         : 
I/flutter ( 3957): Lavc60.3.100 mpeg4
I/flutter ( 3957): 
I/flutter ( 3957):     Side data:
I/flutter ( 3957):       
I/flutter ( 3957): cpb: 
I/flutter ( 3957): bitrate max/min/avg: 0/0/20000000 buffer size: 0 
I/flutter ( 3957): vbv_delay: N/A
I/flutter ( 3957): 
I/flutter ( 3957):   Stream #0:1
I/flutter ( 3957): (und)
I/flutter ( 3957): : Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
I/flutter ( 3957):  (default)
I/flutter ( 3957): 
I/flutter ( 3957):     Metadata:
I/flutter ( 3957):       creation_time   : 
I/flutter ( 3957): 2015-08-07T09:13:02.000000Z
I/flutter ( 3957): 
I/flutter ( 3957):       handler_name    : 
I/flutter ( 3957): L-SMASH Audio Handler
I/flutter ( 3957): 
I/flutter ( 3957):       vendor_id       : 
I/flutter ( 3957): [0][0][0][0]
I/flutter ( 3957): 
I/flutter ( 3957):       encoder         : 
I/flutter ( 3957): Lavc60.3.100 aac
I/flutter ( 3957): 
I/flutter ( 3957): frame=   24 fps=0.0 q=2.0 size=       0kB time=00:00:00.86 bitrate=   0.4kbits/s speed=4.33x    
I/flutter ( 3957): frame=  139 fps=0.0 q=2.0 size=     256kB time=00:00:04.94 bitrate= 423.8kbits/s speed=7.06x    
I/flutter ( 3957): frame=  306 fps=255 q=2.0 size=     512kB time=00:00:10.16 bitrate= 412.6kbits/s speed=8.46x    
I/flutter ( 3957): frame=  523 fps=307 q=2.0 size=     768kB time=00:00:17.40 bitrate= 361.6kbits/s speed=10.2x    
I/flutter ( 3957): frame=  799 fps=363 q=2.0 size=    1024kB time=00:00:26.63 bitrate= 315.0kbits/s speed=12.1x    
I/flutter ( 3957): frame=  901 fps=375 q=1.6 Lsize=    1475kB time=00:00:30.50 bitrate= 396.1kbits/s speed=12.7x    
I/flutter ( 3957): video:1439kB audio:8kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 
I/flutter ( 3957): 1.872120%
I/flutter ( 3957): 
I/flutter ( 3957): [aac @ 0x7eeeb95201c0] Qavg: 65536.000
I/flutter ( 3957): RC
I/flutter ( 3957): 0
`
I'm trying to add subtitles to a video, but every time I try to do so, the succes code returns but doesn't add subtitles to the video. 
I use this command =>
 final command =
        '-i $videoInputPath -filter_complex "subtitles=$subtitlePath:force_style=\'$str\'" -b:v 20M -vcodec mpeg4 $outputPath';

**Comment by astiob** [comment] 2024-03-27 10:26
It seems you’re trying to do it on Android (very different from OS X, which this issue report was about). You probably need to supply your own fonts and pass a `:fontsdir=$path` option to the `subtitles` filter.

**Comment by umityilmazz** [comment] 2024-03-27 23:57
I am aware of the font problems in Android, so I use two functions to save the fonts in order. These give me the following logs.
![image](https://github.com/libass/libass/assets/81180370/31f3755b-274b-450b-8c53-fd03ecee515e)
![image](https://github.com/libass/libass/assets/81180370/2fc4c919-2add-41c1-a2cc-a4f140343384)
When I don't specify a font, it should take the system font, but it doesn't take it and gives this error.
![image](https://github.com/libass/libass/assets/81180370/92163c28-a41f-4d1c-b934-9f3d5bfb2474)

Anyway, as far as I understand, it is a little difficult to do this on android, maybe I will not try anymore.

**Comment by astiob** [comment] 2024-03-28 01:33
I’m afraid I don’t know FFmpegKit and it’s out of scope for this issue tracker, but looking at the code snippet you posted, it looks like you’re supplying a TTF file in place of a Fontconfig configuration file. Fontconfig configuration is an XML file that specifies where to find fonts; it isn’t itself a font.
