### ISSUE TITLE
libass can't parse subtitles contain "\"

### ISSUE THREAD

**Issue by Adonis-Song** [libass/libass#462] opened 2020-12-11 08:40 UTC
How does  libass parse ass with "\\"?
I use ass to create karaoke effect, but when subtitle contains "\\", libass will show wrong text, I read source code ,find you parse special characters:

```c
   if (*p == '\\') {
         if ((p[1] == 'N') || ((p[1] == 'n') &&
                      (render_priv->state.wrap_style == 2))) {
            p += 2;
            *str = p;
            return '\n';
        } else if (p[1] == 'n') {
            p += 2;
            *str = p;
            return ' ';
        } else if (p[1] == 'h') {
            p += 2;
            *str = p;
            return NBSP;
        } else if (p[1] == '{') {
            p += 2;
            *str = p;
            return '{';
        } else if (p[1] == '}') {
            p += 2;
            *str = p;
            return '}';
        }
    } 

```

So if my ass event is " {\20}\\{\k20}h{\k40}e{\k30}l{\k39}l{\k40}0  ",   libass will think subtitle is “ {\k20}hello ", but actually subtitle is  " \\hello". 
Can I do some thing to avoid this ?

**Comment by astiob** [comment] 2020-12-11 14:32
This is effectively a duplicate of #194.

Add an invisible character (e. g. U+200B ZERO WIDTH SPACE) after the backslash. And make sure it has disabled underline and strikethrough, as libass currently has a bug (#463) that causes it to add a visible underline/strikethrough to characters like this.

More problematic is displaying an opening brace (“{”): you can’t do that in a VSFilter-compatible way. See the last comments in #194: if you’re converting/creating subtitles on the fly for libass, use `\{`, but if you want to distribute the ASS file, use a full-width brace and negative font spacing or similar.

(I’ve edited your post slightly to fix missing backslashes in Markdown. I hope I did it right, but if not, please edit it again.)

**Closed by astiob** 2020-12-11 14:32 UTC

**Comment by Adonis-Song** [comment] 2020-12-14 02:55
str.replace(/\\/g, '\\\u2060') not work for me,  
str.replace(/\\/g, '\\\u200b') work, 

thanks
