### ISSUE TITLE
Rendering: effects show different?

### ISSUE THREAD

**Issue by hooke007** [libass/libass#696] opened 2023-06-24 17:53 UTC
### Screenshots

![Snipaste_2023-06-24_18-51-48](https://github.com/libass/libass/assets/41094733/abedd8b8-20eb-413e-a3aa-ff9e59edc24a)

### Description of the issue

See above.

### libass version

master (mpv)

### ASS Sample

[EXsub.zip](https://github.com/libass/libass/files/11857836/EXsub.zip)

### Special Fonts

I uploaded or linked to the required font

### System Information

WIN10

### Log

N/A

### Additional info

N/A

**Comment by astiob** [comment] 2023-06-24 19:04
Here’s what I see in XySubFilter (xy-VSFilter) 3.2.0.806:
<img width="640" alt="Hant mkv_snapshot_00 02 920_XySubFilter" src="https://github.com/libass/libass/assets/515193/3fccc6bf-9e1f-4c76-8eb9-d461e3ef40bb">
So libass/mpv behaviour is correct.

Here’s what I see with the internal subtitle renderer of MPC-HC 2.0.0 (973b644a3) at 1280×720 (which is the script’s native resolution):
<img width="640" alt="Hant mkv_snapshot_00 02 920_MPC-HC" src="https://github.com/libass/libass/assets/515193/23e4c405-4065-44a4-94bb-b02102df1afe">
and when I resize the output window, it looks different at each size. Increasing the output resolution drags some of the leftmost points out, similar to your screenshot. At some point, the part on the right (the left stem of け) seems as if clipped. And lowering the resolution causes the leftmost dots to disappear entirely and leave behind a circle of dots, and lowering further causes the whole text to disappear completely.

So this is an MPC-HC bug.

**Comment by astiob** [comment] 2023-06-24 19:08
A wild guess, but I suspect this may be caused by MPC-HC [rounding all drawing coordinates to whole screen pixels](https://github.com/clsid2/mpc-hc/blob/a537bfdee6863c0d0cb9412060078d2782c70803/src/Subtitles/RTS.cpp#L687). The drawings in this script use 1/32th part of a pixel. Rounding them to whole pixels could unsurprisingly make the output look different from what was intended.

**Comment by astiob** [comment] 2023-06-24 19:16
I’m closing this because I believe there’s no libass problem here, but if I’ve misunderstood anything, let me know.

You may want to report this to [clsid2/mpc-hc](https://github.com/clsid2/mpc-hc/issues), although there’s no guarantee that this will be changed, seeing as the rounding was originally added in an attempt to reduce ugliness when rescaling drawings to different output resolutions. I’m not sure I’ve seen evidence that it ever actually helped on that front, though.

**Closed by astiob** 2023-06-24 19:16 UTC
Labels: compatibility, not our bug

**Comment by hooke007** [comment] 2023-06-24 19:17
I used mpc-be(vsfilter) not hc...

**Comment by astiob** [comment] 2023-06-24 19:18
MPC-BE is a fork of MPC-HC and hence uses much of the same code.

**Comment by hooke007** [comment] 2023-06-24 19:20
Yeah I found the same line in BE.
