### ISSUE TITLE
Try to parse script properties even if missing "[Script Info]"

### ISSUE THREAD

**Issue by dyphire** [libass/libass#708] opened 2023-09-28 11:52 UTC
Currently, both libass and vsfilter can parse and render subtitle files with missing [Script Info]. 
But libass is still not smart enough to parse script properties without [Script Info]. This causes libass to incorrectly render subtitles without parsing properties such as PlayRes.

This is a vsfilter compatibility issue and may need to be fixed. ref https://github.com/mpv-player/mpv/issues/11482#issuecomment-1732540587

I have a quick patch to fix the compatibility for libass, but there may be a better solution.
This is the patch:
```diff
From 4cfbbe2f70c02e156785de9bc12d124b6914bd29 Mon Sep 17 00:00:00 2001
From: dyphire <qimoge@gmail.com>
Date: Wed, 27 Sep 2023 22:48:04 +0800
Subject: [PATCH] Try to parse script properties even if missing "[Script Info]"

---
 libass/ass.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/libass/ass.c b/libass/ass.c
index 0679483..c0734d2 100644
--- a/libass/ass.c
+++ b/libass/ass.c
@@ -1143,7 +1143,7 @@ mem_fail:
 static int process_line(ASS_Track *track, char *str)
 {
     skip_spaces(&str);
-    if (!ass_strncasecmp(str, "[Script Info]", 13)) {
+    if (!ass_strncasecmp(str, "[Script Info]", 13) || !ass_strncasecmp(str, "ScriptType:", 11)) {
         track->parser_priv->state = PST_INFO;
     } else if (!ass_strncasecmp(str, "[V4 Styles]", 11)) {
         track->parser_priv->state = PST_STYLES;
-- 
```

**Comment by TheOneric** [comment] 2023-10-08 15:37
Duplicate of #19 

Your patch would break files in which `ScriptType` appears in a non-`[Script Info]` section which I believe to be a bad idea. Fixing this properly is something we ultimately want to do at some point, but since such files are rare it has not been a high priority so far.
If you know of a source which consistently releases files missing `[Script Info]` please let us know (and better also contact them to make their releases more portable). Also see my latest comment in #19.

**Closed by TheOneric** 2023-10-08 15:37 UTC
Labels: duplicate, compatibility
