### ISSUE TITLE
RTL Karaoke Effect

### ISSUE THREAD

**Issue by youkaclub** [libass/libass#406] opened 2020-06-28 22:26 UTC
Hello, 
Thank you for creating and maintaining this awesome lib.
I'm using libass in [Youka](https://github.com/youkaclub/youka-desktop) - an karaoke maker, especially for the beautiful karaoke effect.
Everything works great for LTR languages, but I can't make it works for RTL (Arabic and Hebrew), the color is fill the words from left to right instead of right to left.
I followed these issues (#292, #295) suggestions without success.
Any idea how to make it works?

**Comment by TheOneric** [comment] 2020-06-29 00:32
Probably a duplicate of #221.

Unfortunately complications with backwards and *VSFilter-compatibility make it hard (although probably not impossible) for libass to handle RTL text in a way one would normally consider “proper” and “sane” (but not in the context of VSFilter-compatibility).  
astiob's comments ([[1]](https://github.com/libass/libass/issues/295#issuecomment-356055686),  [[2]](https://github.com/libass/libass/issues/295#issuecomment-354893352)) in #295 go more indepth on this.
 
RTL subs assuming (some) of *VSFilters RTL-weirdnesses **do** exist. See eg #374.

Until a compatibility-friendly solution has been implemented<sup>[1]</sup>, I'm afraid you'll have to rely on the workaround from issue 221.

---

**[1]**: Even with a libass extension addressing the issue, subs would still soft-break in *VSFilters.

**Comment by lenaten** [comment] 2020-06-29 08:02
Thanks @TheOneric for the prompt response.

I read all the issues you mentioned but still don’t understand which part I should (fork and) change to make it work.

1. libass - auto detect encoding based on font didn’t work 
2. vsfilter?
3. ass file - add rtl unicode. I don’t understand how the line should be written and if it’s even related to karaoke effect 

I’ll do whatever it takes to make it work. 
Legacy compatibility is not important for me because I control the player.

Can you advise and direct me which part I should change?

**Comment by youkaclub** [comment] 2020-06-29 08:03
Thanks @TheOneric for the prompt response.

I read all the issues you mentioned but still don’t understand which part I should (fork and) change to make it work.

libass - auto detect encoding based on font didn’t work
vsfilter?
ass file - add rtl unicode. I don’t understand how the line should be written and if it’s even related to karaoke effect
I’ll do whatever it takes to make it work.
Legacy compatibility is not important for me because I control the player.

Can you advise and direct me which part I should change?

**Comment by TheOneric** [comment] 2020-06-29 18:23
> I read all the issues you mentioned but still don’t understand which part I should (fork and) change to make it work. The font and text looks great, it’s just the karaoke effect.

Apart from the duplicate those were mostly meant to illustrate the general struggle with “sane” RTL behaviour in ASS and that backwards compatibility is not just a theoretical concern.  
If everything else RTL related is working good enough for your usecase, you don't have to worry about that for now.

  
> I’ll do whatever it takes to make it work. […] 
> I mean, it’s just a code, there must be a way to make it work within few hours of coding, isn’t it?

I applaud your enthusiasm and optimism :)

<br/>

> Backward compatibility is not important to me because I control the player, and my code generate the ass file in real time from scratch.
> […] 
> Can you advise and direct me which part I should change?

Not having to worry about compatibility, generating the ASS files yourself and being an API user certainly gives you more options.  
You could either try to replace `\kf` tags with animated `\clip`s as mentioned in 221 – in that case no patching/forking will be required.

Or you can go and apply some non-compatible (and  thus non-upstreamable) patches to meet your needs.
If you decide to make this effort – and since karaoke seems to be your primary concern – you probably also want to apply those unmerged patches *(add `.patch` to url to get a format-patch)*:

  1) [astiob's `\kf0` patch](https://github.com/astiob/libass/commit/1225c1d457d1b287bf4291cdcbe5bb0cf4927950) (no associated pr)
  2) [MrSmile's karaoke patch](https://github.com/libass/libass/pull/343/commits/255f8d79d36f39415998a272c2245326d35c4ab0) (from pr #343) 

Both apply cleanly on current git master.  

The second one gets rid of all karaoke regressions *(compared to 0.14)* I've encountered . (eg I've seen many instances like #357)
I should however point out that tbh I don't fully understand the implications of the changes and apparently [there are still problems with it](https://github.com/libass/libass/pull/343#issuecomment-551209460). However, in my case applying it yiielded significant improvements (only tested with LTR). You may want to test it with your usecase beforehand.
Alternatively you could base your libass version on 0.14, **but** there are also some karaoke [issues in 0.14 that are only correct in git master with this patch](https://github.com/libass/libass/issues/216#issuecomment-643685186)

As for where to start looking when implementing a patch: I'm not that familiar with the specifics of karaoke in libass, but you probably want to take a look at [ass_parse.c:830](https://github.com/libass/libass/blob/master/libass/ass_render.c#L830) and [ass_render.c:process_karaoke_effects](https://github.com/libass/libass/blob/master/libass/ass_parse.c#L923) 

---

You may be already aware of the following, but as I found this to happen surprisingly often allow some comments about forking vs maintaining a patch set.  

Since you only want some specific limited patches a *fork* (cloning and branching off with a separate git history) is probably overkill and will only increase overhead by either a lot of cherry picking from upstream or frequent force-pushs to rebase to upstream.  
It seems to me a patch set would fit your needs better. You could just include upstream-libass as a submodule and only have the patches in your repo, which could then be automatically applied with eg `quilt` (it's easy to import format-patches with quilt). This way no force-pushs are required, and it is easy to integrate upstream changes (`git submodule update libass`). Changes would only be necessary if the patches themselves need to be updated – be it for problems with the patch itself or due to upstream changes. And you get to keep the history of your patches in a easily accessible way.
With a fork that force pushes there would be no patch-history and with cherry-picking upstream changes, your patch's history would be mangled with upstream history.

Ofc it is completly valid to choose a fork over maintaining a patch set anyway due to eg personal preference or any other reason.

**Comment by youkaclub** [comment] 2020-06-29 20:11
Thanks @TheOneric for taking your time to help me, I’ll try your suggestions and reference here my work for future RTL users.

Regard the kf tag, I’m using the K tag, should I use kf instead? I read the docs but can’t get the difference between them.

**Comment by TheOneric** [comment] 2020-06-29 21:13
Ohh, I forgot to mention: Since you are an API user doing on the fly conversions and *VSFilter compatibility is thus not an issue, you might also want to take a look at libass' ASS extensions. Non-final docs: https://github.com/libass/libass/wiki/Libass'-ASS-Extensions

> Regarding the kf tag, I’m using the K tag, should I use kf instead? I read the docs but can’t get the difference between them.

There is no difference, `\K` and `\kf` are aliases. `\K` and `\k` are different though.

**Comment by youkaclub** [comment] 2020-06-29 22:55
Regarding the clip option, is it a completely \k replacement? What’s the downsides? Can you refer me to some usage example? I found only a general examples, not for karaoke effect.

**Comment by astiob** [comment] 2020-06-30 00:14
In VSFilter (de facto standard ASS), adding `{\frz180\frx180\fry180}` to your lines (or defining your style equivalently) makes [each block fill from right to left](https://chortos.selfip.net/~astiob/screens/karaoke-transformed/). Unfortunately, I think this doesn’t work in libass at the moment.

The only standard-ASS workaround I can suggest off the top of my head—which I’ve suggested before in similar situations—is to have two otherwise-identical lines of different colours with \clip rectangles animated using \t. Unfortunately, to do this, you need to know the coordinates of your text. (Then again, more complex karaoke effects require this anyway even in left-to-right text.)

If you’re going the route of modifying libass’s source code, you “should” be able to get the coordinates from within the rendering function. I’d _like_ to be able to say this is easy, but unfortunately karaoke tags in libass are currently a bit of a mess and don’t work fully properly (as evidenced by the pending patches @TheOneric linked above). In other words, even we, libass developers, don’t currently have a full & proper understanding of how to get the right coordinates for this. ☹️

If your use cases are simple enough (one override tag block = one karaoke block), you might be able to do this entirely at the stage when combined bitmaps are created (search for `Combined` in `ass_render.c`) and use the combined bitmaps’ coordinates, although IIRC they can include some transparent padding.

**Comment by youkaclub** [comment] 2020-06-30 07:54
Thanks @astiob for clarifying the situation, I’m still hoping that I will be able to figure it out.

**Comment by astiob** [comment] 2020-10-26 23:43
@youkaclub `{\frz180\frx180\fry180}` now creates a right-to-left fill in libass (starting with version 0.15.0 that I’ll release in a moment).

You should also watch #441, which will have severe implications for right-to-left text, but it’s _not_ going into today’s 0.15.0 release.

**Closed by astiob** 2020-10-26 23:43 UTC

**Comment by youkaclub** [comment] 2020-10-26 23:52
❤️

**Comment by astiob** [comment] 2020-10-26 23:54
Oh, you probably also want to enable the new `ASS_FEATURE_BIDI_BRACKETS` as per #409, specifically 66dba8dd21bbf81b25b26e2556c404006f80a43c. It has nothing to do with karaoke specifically, but it improves handling of bidirectional text. Also make sure to set the ASS Encoding field to -1, but I imagine you’re already doing that.

Or just enable `ASS_FEATURE_INCOMPATIBLE_EXTENSIONS`, which will cover bidi brackets _and_ the upcoming later change I mentioned earlier, as well as any future quality improvements, at the cost of potentially larger breaking changes.

(If you’re still developing your application… I can’t tell from the Git repository.)

**Comment by youkaclub** [comment] 2020-10-27 00:04
thanks @astiob, I'm still developing Youka but now as closed source (no one has contributed anyway).
I've added your email address as Youka premium user - in case you interested in karaoke.

**Comment by realfinder** [comment] 2021-03-08 17:45
@youkaclub 

there are many methods to make arabic kara, the one I made backthen is (it was in Arabic and this is English Translation)

> I modified the "Tadween" program to fit the right2left karaoke aegisub script
> http://www.mediafire.com/file/g83194o4xty8v8g/Tadween_aegisub_mod.rar/file
> Now any foreign template can be used to make Arabic karaoke
> Of course, the karaoke lua script that supports right to left (not the old lua Arabic karaoke one) is attached to the program, the old script may not work, and the modern (right2left) script needs at least aegisub 2.1.9. Read the attached file to know how to properly install it. 
> The use is very easy, use the writing program to write and it will copy the modified text for you automatically, you only have to paste it in the Aegisub box and then timing the words and apply right2left. 
> The modified source code and an additional lua script in case of diacritics movements in the atmosphere, in addition to the above program, you can find them here  https://www.mediafire.com/folder/7utxyqni29wek/Tadween_aegisub_mod?fbclid=IwAR14o5JhiarDz4dIoo2qjYFv9QuAH-m9jertdR5vw7DPRS6E3FoMolOIk_0 (keep in mind that it's GNU v2 so you can't use code from it unless you open your code)

IIRC, it was need LRO in libass cuz https://code.google.com/archive/p/libass/issues/86 but after https://github.com/libass/libass/pull/441 I think it not need that

anyway, if the libass can make the K/kf tags work from right to left for right to left Languages in Encoding = -1, it will be something welcomed since it will not break vsfilter scripts compatibility but of course like any "Encoding = -1" thing it will not work in vsfilter
