### ISSUE TITLE
Rendering: Arabic font style appears as squares

### ISSUE THREAD

**Issue by MrJktra** [libass/libass#633] opened 2022-07-14 20:50 UTC
### **Using MPC-HC (64-bit) V 1.9.22 (734896a23) with internal rendering**
![Using MPC-HC (64-bit) V 1 9 22 (734896a23) with internal rendering ](https://user-images.githubusercontent.com/101983929/179073853-dd95dbcc-d4dd-4844-a8dc-e945034b7efc.png)

### **Using mpv-x86_64-20220710-git-0044c19**
![Using mpv-x86_64-20220710-git-0044c19](https://user-images.githubusercontent.com/101983929/179072368-c073af3a-34fd-4caf-accd-b0f894aec3cf.png)

![Using mpv-x86_64-20220710-git-0044c19 2](https://user-images.githubusercontent.com/101983929/179074209-6fec9e35-f81b-45b4-9a0b-71e94b2dbfc2.png)

### **Using MPC-HC (64-bit) V 1.9.22 (734896a23) with XySubFilter**
![Using MPC-HC (64-bit) V 1 9 22 (734896a23) with XySubFilter with libass version 20220516](https://user-images.githubusercontent.com/101983929/179073186-83461c4a-8c81-4728-af99-6290e0b5f4cc.png)

[Link to this](https://github.com/Masaiki/xy-VSFilter)

### Description of the issue

See the pictures for details
Font: MCS Diwani0 S_I normal.
[diwani.zip](https://github.com/libass/libass/files/9115219/diwani.zip)

### libass version

idk i'm using mpv-x86_64-20220710-git-0044c19

### Is it a regression?

same issue with previous mpv version

### ASS Sample

[in 22 min exactly.zip](https://github.com/libass/libass/files/9115042/in.22.min.exactly.zip)

### Special Fonts

I uploaded or linked to the required font

### System Information

Processor:	Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz   2.90 GHz
Installed RAM:	16.0 GB (15.9 GB usable)
System type:	64-bit operating system, x64-based processor
Edition:	Windows 10 Pro
Version:	20H2
OS build:	19042.1645
Experience:	Windows Feature Experience Pack 120.2212.4170.0

### Log

[mpv log.txt](https://github.com/libass/libass/files/9115260/mpv.log.txt)

**Comment by TheOneric** [comment] 2022-07-14 22:21
Thanks for your detailed report!
I suspect this is the same issue as #292, with Diwani using the obsolete, Windows-specific “Traditional Arabic Windows 3.1” font page. HarfBuzz only [very recently](https://github.com/harfbuzz/harfbuzz/pull/3063#event-6834979353=) gained support for those fonts in a cross-platform way. Judging by the HarfBuzz version indicated in your log, the support should already be present for you, but it seems we also need to hook it up somehow on our side (as already speculated in #292).

However, I'm not sure how to definitely confirm a font uses this codepage. @astiob’s [`debug-fonts` branch](https://github.com/astiob/libass/commit/27b175edb1295dd92b6107ccd1620a53cee16712) just lists them as Unicode (when run on Linux) iinm *(full info below; and so does Fontforge accompanied by warnings about possibly misplaced glyphs)*. The glyph positions in Fontforge look suspiciously similar to the ones from an earlier font sample confirmed to use “Traditional Arabic Windows 3.1”.

```
libass: get_font_info: platform_id=Unicode, name_id=1, encoding_id=0, language_id=0, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Unicode, name_id=2, encoding_id=0, language_id=0, name=[Agfa MCS]
libass: get_font_info: platform_id=Unicode, name_id=4, encoding_id=0, language_id=0, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Unicode, name_id=6, encoding_id=0, language_id=0, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Macintosh, name_id=1, encoding_id=0, language_id=0, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Macintosh, name_id=2, encoding_id=0, language_id=0, name=[Agfa MCS]
libass: get_font_info: platform_id=Macintosh, name_id=4, encoding_id=0, language_id=0, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Macintosh, name_id=6, encoding_id=0, language_id=0, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Microsoft, name_id=1, encoding_id=0, language_id=0x0409, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Microsoft, name_id=2, encoding_id=0, language_id=0x409, name=[Agfa MCS]
libass: get_font_info: platform_id=Microsoft, name_id=4, encoding_id=0, language_id=0x0409, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: platform_id=Microsoft, name_id=6, encoding_id=0, language_id=0x409, name=[MCS Diwani0 S_I normal.]
libass: get_font_info: FreeType's family_name=[MCS Diwani0 S_I normal.]
libass: get_font_info: OS/2 table version 0, fsSelection 0xB340 (WWS bit 256), usWeightClass 5
libass: get_font_info: cmap for platform_id=Unicode, encoding_id=0
libass: get_font_info: cmap for platform_id=Macintosh, encoding_id=0, language_id+1=0
libass: get_font_info: cmap for platform_id=Microsoft, encoding_id=0
libass: get_font_info: style_flags 0x1
libass: get_font_info: head table version 1, flags 0x0, Mac style 0x0
libass: get_font_info: hhea table version 1, caret slope rise/run 1/0 = inf
libass: get_font_info: post table version 2, italicAngle 0
libass: get_font_info: no PCLT table
libass: get_font_info: no fond table
libass: new font:
libass:   family: 'MCS Diwani0 S_I normal.'
libass:   fullname: 'MCS Diwani0 S_I normal.'
libass:   slant: 100
libass:   weight: 5
libass:   width: 100
libass:   postscript_name: (null)

libass: get_font_info: platform_id=Unicode, name_id=1, encoding_id=0, language_id=0, name=[AGA Aladdin Regular]
libass: get_font_info: platform_id=Unicode, name_id=2, encoding_id=0, language_id=0, name=[Regular]
libass: get_font_info: platform_id=Unicode, name_id=4, encoding_id=0, language_id=0, name=[AGA Aladdin Regular]
libass: get_font_info: platform_id=Unicode, name_id=6, encoding_id=0, language_id=0, name=[AGA-AladdinRegular]
libass: get_font_info: platform_id=Macintosh, name_id=1, encoding_id=0, language_id=0, name=[AGA Aladdin Regular]
libass: get_font_info: platform_id=Macintosh, name_id=2, encoding_id=0, language_id=0, name=[Regular]
libass: get_font_info: platform_id=Macintosh, name_id=4, encoding_id=0, language_id=0, name=[AGA Aladdin Regular]
libass: get_font_info: platform_id=Macintosh, name_id=6, encoding_id=0, language_id=0, name=[AGA-AladdinRegular]
libass: get_font_info: platform_id=Microsoft, name_id=1, encoding_id=0, language_id=0x0409, name=[AGA Aladdin Regular]
libass: get_font_info: platform_id=Microsoft, name_id=2, encoding_id=0, language_id=0x409, name=[Regular]
libass: get_font_info: platform_id=Microsoft, name_id=4, encoding_id=0, language_id=0x0409, name=[AGA Aladdin Regular]
libass: get_font_info: platform_id=Microsoft, name_id=6, encoding_id=0, language_id=0x409, name=[AGA-AladdinRegular]
libass: get_font_info: FreeType's family_name=[AGA Aladdin Regular]
libass: get_font_info: OS/2 table version 0, fsSelection 0xB340 (WWS bit 256), usWeightClass 5
libass: get_font_info: cmap for platform_id=Unicode, encoding_id=0
libass: get_font_info: cmap for platform_id=Macintosh, encoding_id=0, language_id+1=0
libass: get_font_info: cmap for platform_id=Microsoft, encoding_id=0
libass: get_font_info: style_flags 0x1
libass: get_font_info: head table version 1, flags 0x0, Mac style 0x0
libass: get_font_info: hhea table version 1, caret slope rise/run 1/0 = inf
libass: get_font_info: post table version 2, italicAngle 0
libass: get_font_info: PCLT table version 2, style 0x0 (posture 0)
libass: get_font_info: no fond table
libass: new font:
libass:   family: 'AGA Aladdin Regular'
libass:   fullname: 'AGA Aladdin Regular'
libass:   slant: 100
libass:   weight: 5
libass:   width: 100
libass:   postscript_name: AGA-AladdinRegular
```

**Comment by TheOneric** [comment] 2022-07-22 22:44
> However, I'm not sure how to definitely confirm a font uses this codepage.

As it turns out there actually is some [documentation]() about those fonts:

 - They have cmaps for platform ID 3 (`Microsoft`) with encoding 0.
    (Unicode fonts use platform id 0, or platform id 3 with encoding either as 1 or 10 [[ref]]())
 - it is explicitily noted, that while those fonts might have additional cmaps, those must not be used and are likely broken.
 - only codepoints  0xF100 to 0xF1FF are used for `ARABIC_CHARSET_SIMPLIFIED` fonts, 0xF200 to 0xF2FF for `ARABIC_CHARSET_TRADITIONAL`
   (this is similar but different from regular symbol fonts which use 0xF020 to 0xF0FF)
 - the doc contains an encoding mapping table allowing to check the individual glyph assignments
 
 Diwani fits those *(using `ARABIC_CHARSET_TRADITIONAL`)* including the placement of the glyphs I checked; so yes this is indeed a duplicate of #292.

**Closed by TheOneric** 2022-07-22 22:44 UTC
Labels: compatibility, fonts
