### ISSUE TITLE
build: Macro fails to identify Mac OS X version

### ISSUE THREAD

**Issue by toreonify** [libass/libass#837] opened 2024-10-13 17:30 UTC
### libass version

5298859c298d3c570d8d7e3b883a0d63490659b8

### How did you invoke configure?

CC=gcc-mp-7 ./configure

### System Information

OS: Mac OS X 10.5.8 PowerPC
CPU: PowerPC G5
MacPorts: 2.10.2

### Toolchain

```
gcc-mp-7 (MacPorts gcc7 7.5.0_4) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
@(#)PROGRAM:ld  PROJECT:ld64-127.2
configured to support archs: i386 x86_64 ppc ppc64 armv6 armv7
LTO support using: LLVM version 3.3
```

### Log of the error

```
  CC       libass/ass_coretext.lo
libass/ass_coretext.c: In function 'get_font_file':
libass/ass_coretext.c:92:30: error: 'kCTFontURLAttribute' undeclared (first use in this function); did you mean kCTFontSizeAttribute'?
     else if (CHECK_AVAILABLE(kCTFontURLAttribute, macOS 10.6, *)) {
                              ^
libass/ass_coretext.c:38:50: note: in definition of macro 'CHECK_AVAILABLE'
 #define CHECK_AVAILABLE(sym, ...) (!!(intptr_t) &sym)
                                                  ^~~
libass/ass_coretext.c:92:30: note: each undeclared identifier is reported only once for each function it appears in
     else if (CHECK_AVAILABLE(kCTFontURLAttribute, macOS 10.6, *)) {
                              ^
libass/ass_coretext.c:38:50: note: in definition of macro 'CHECK_AVAILABLE'
 #define CHECK_AVAILABLE(sym, ...) (!!(intptr_t) &sym)
                                                  ^~~
make[1]: *** [libass/ass_coretext.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

### Additional info

In `libass/ass_coretext.c` code for Mac OS X higher or equal to 10.6 is enclosed with check to `__MAC_10_6` :
```c
static char *get_font_file(CTFontDescriptorRef fontd)
{
    CFURLRef url = NULL;
    if (false) {}
#ifdef __MAC_10_6
    // Declared in SDKs since 10.6, including iOS SDKs
    else if (CHECK_AVAILABLE(kCTFontURLAttribute, macOS 10.6, *)) {
        url = CTFontDescriptorCopyAttribute(fontd, kCTFontURLAttribute);
    }
#endif
#if !TARGET_OS_IPHONE && (!defined(__MAC_10_6) || __MAC_OS_X_VERSION_MIN_REQUIRED < __MAC_10_6)
    // ATS is declared deprecated in newer macOS SDKs
    // and not declared at all in iOS SDKs
    else {
        CTFontRef font = CTFontCreateWithFontDescriptor(fontd, 0, NULL);
        if (!font)
            return NULL;
        ATSFontRef ats_font = CTFontGetPlatformFont(font, NULL);
        FSRef fs_ref;
        if (ATSFontGetFileReference(ats_font, &fs_ref) == noErr)
            url = CFURLCreateFromFSRef(NULL, &fs_ref);
        CFRelease(font);
    }
#endif
```

But `__MAC_10_6` is defined in [10.5 SDK](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.5.sdk/usr/include/Availability.h). 

```c
#ifndef __AVAILABILITY__
#define __AVAILABILITY__


#define __MAC_10_0      1000
#define __MAC_10_1      1010
#define __MAC_10_2      1020
#define __MAC_10_3      1030
#define __MAC_10_4      1040
#define __MAC_10_5      1050
#define __MAC_10_6      1060
#define __MAC_NA        9999   /* not available */

#define __IPHONE_2_0     20000  
#define __IPHONE_NA      99999

#include <AvailabilityInternal.h>
```

With `__MAC_10_6` available, compilation fails as it tries to use code for 10.6 or later. Rewriting conditional statement like this fixes incorrect detection and library works fine on 10.5.8  (tested with FFmpeg playback). As condition for OS version is not changed drastically, it should work correctly on higher OS versions.

```patch
--- libass/ass_coretext.c	2024-10-12 22:19:55.000000000 +0300
+++ libass/ass_coretext.c	2024-10-12 22:21:30.000000000 +0300
@@ -87,25 +87,21 @@
 static char *get_font_file(CTFontDescriptorRef fontd)
 {
     CFURLRef url = NULL;
-    if (false) {}
-#ifdef __MAC_10_6
-    // Declared in SDKs since 10.6, including iOS SDKs
-    else if (CHECK_AVAILABLE(kCTFontURLAttribute, macOS 10.6, *)) {
-        url = CTFontDescriptorCopyAttribute(fontd, kCTFontURLAttribute);
-    }
-#endif
-#if !TARGET_OS_IPHONE && (!defined(__MAC_10_6) || __MAC_OS_X_VERSION_MIN_REQUIRED < __MAC_10_6)
+#if !TARGET_OS_IPHONE && (__MAC_OS_X_VERSION_MIN_REQUIRED < __MAC_10_6)
     // ATS is declared deprecated in newer macOS SDKs
     // and not declared at all in iOS SDKs
-    else {
-        CTFontRef font = CTFontCreateWithFontDescriptor(fontd, 0, NULL);
-        if (!font)
-            return NULL;
-        ATSFontRef ats_font = CTFontGetPlatformFont(font, NULL);
-        FSRef fs_ref;
-        if (ATSFontGetFileReference(ats_font, &fs_ref) == noErr)
-            url = CFURLCreateFromFSRef(NULL, &fs_ref);
-        CFRelease(font);
+    CTFontRef font = CTFontCreateWithFontDescriptor(fontd, 0, NULL);
+    if (!font)
+        return NULL;
+    ATSFontRef ats_font = CTFontGetPlatformFont(font, NULL);
+    FSRef fs_ref;
+    if (ATSFontGetFileReference(ats_font, &fs_ref) == noErr)
+        url = CFURLCreateFromFSRef(NULL, &fs_ref);
+    CFRelease(font);
+#else
+    // Declared in SDKs since 10.6, including iOS SDKs
+    if (CHECK_AVAILABLE(kCTFontURLAttribute, macOS 10.6, *)) {
+        url = CTFontDescriptorCopyAttribute(fontd, kCTFontURLAttribute);
     }
 #endif
     if (!url)

```

harbuzz uses similar approach with `MAC_OS_X_VERSION_MIN_REQUIRED`: https://github.com/harfbuzz/harfbuzz/pull/1578/commits/87ea0abba236d784a8ecfb47faf94e8b8f1c240d.

Apple mentions in `Availability.h` that macros with OS version like `__MAC_10_6` aren't supposed to be used, their value must be used directly with `__MAC_OS_X_VERSION_MIN_REQUIRED`: 

```c
It is also possible to use the *_VERSION_MIN_REQUIRED in source code to make one
source base that can be compiled to target a range of OS versions.  It is best
to not use the _MAC_* and __IPHONE_* macros for comparisons, but rather their values.
That is because you might get compiled on an old OS that does not define a later
OS version macro, and in the C preprocessor undefined values evaluate to zero
in expresssions, which could cause the #if expression to evaluate in an unexpected
way.

    #ifdef __MAC_OS_X_VERSION_MIN_REQUIRED
        // code only compiled when targeting Mac OS X and not iPhone
        // note use of 1050 instead of __MAC_10_5
        #if __MAC_OS_X_VERSION_MIN_REQUIRED < 1050
            // code in here might run on pre-Leopard OS
        #else
            // code here can assume Leopard or later
        #endif
    #endif
```

**Comment by astiob** [comment] 2024-10-13 18:22
> Apple mentions in `Availability.h` that macros with OS version like `__MAC_10_6` aren't supposed to be used, their value must be used directly with `__MAC_OS_X_VERSION_MIN_REQUIRED`

I think you misunderstand the quoted text. Apple is saying the macros may be undefined and produce unexpected logic flow, which we account for (it’s not unexpected to us). Your case is the opposite: you have the macro defined but not the symbol for some reason.

Two other people on this tracker have previously reported using 10.5.8, and libass built without this issue for both of them. The latest case was https://github.com/libass/libass/issues/826. It would be good to understand what’s different in your case.

@barracuda156 Could you help here? Does your 10.5 SDK define `__MAC_10_6` in `Availability.h`?

These macro checks were discussed at length when we introduced them, and I had wanted stricter ones, but this was ultimately deemed safe. It would be good to understand where we went wrong.

**Comment by rcombs** [comment] 2024-10-13 18:34
I guess we could just do an autoconf check for the existence of the `kCTFontURLAttribute` symbol? (I'm still very confused about why anybody is trying to build this project against a 16-year-old SDK, and this is liable to stop working whenever we start adopting newer C features anyway…)

**Comment by astiob** [comment] 2024-10-13 18:34
Or perhaps @saxfun is a better pick. Could you check if your 10.5 SDK defines `__MAC_10_6` in `/usr/include/Availability.h`? If it does, I don’t understand why it builds for you but not for toreonify.

**Comment by astiob** [comment] 2024-10-13 18:35
> I guess we could just do an autoconf check for the existence of the `kCTFontURLAttribute` symbol?

We did that before we added support for 10.5. This symbol is not used on 10.5.

> I'm still very confused about why anybody is trying to build this project against a 16-year-old SDK

Some people actually keep old machines running. Old machines have old SDKs.

**Comment by astiob** [comment] 2024-10-13 18:36
Oh, perhaps you mean an _additional_ autoconf check for that symbol. We could do that, but we could also just use Apple’s recommended macro checks instead of trying to oversimplify things.

**Comment by astiob** [comment] 2024-10-13 18:49
Although technically, an autoconf check would be the safest bet, of course.

https://github.com/libass/libass/commit/927565a0365339d8dde2c644a8cb98ff497ff263 seems to be the last version of my commit that predated the switch to `__MAC_10_6`. It has this:

```c
#if TARGET_OS_IPHONE || __MAC_OS_X_VERSION_MAX_ALLOWED >= 1060
    else if ...
#endif
#if !TARGET_OS_IPHONE && __MAC_OS_X_VERSION_MIN_REQUIRED < 1060
    else ...
#endif
```

with the following explanation:

```
There are multiple ways to determine whether the newer symbol is
declared at all. To keep it simple, avoid a configure check and stick
to a simple macro check.

In older versions of Apple's SDK, Core Text headers have reacted to
"Mac OS X version max allowed" control-knob macros and marked newer
APIs "unavailable" (making any use of them a compilation error) even
if they were known to that SDK. Hence, use one of those same macros
(which are still provided and used in newer SDKs although they no
longer mark symbols unavailable) as our detection mechanism.

In 10.5-10.6 SDKs, Core Text used AvailabilityMacros.h and its
MAC_OS_X_VERSION_MAX_ALLOWED; in later versions, it switched to
Availability.h and its __MAC_OS_X_VERSION_MAX_ALLOWED with two leading
underscores. Both headers are available since 10.5, and Availability.h
is more flexible as it has version iOS macros in addition to macOS,
which we may need for other APIs in the future, so just use
Availability.h.
```

Actually, now that I look at it, the version we settled upon wasn’t even much simpler:

```c
#ifdef __MAC_10_6
    // Declared in SDKs since 10.6, including iOS SDKs
    else if ...
#endif
#if !TARGET_OS_IPHONE && (!defined(__MAC_10_6) || __MAC_OS_X_VERSION_MIN_REQUIRED < __MAC_10_6)
    else ...
#endif
```

I clearly did look at the 10.5 SDK when writing that code and that commit message, so how did we end up with this? Oh well.

Anyway, what do you prefer? The macros or an extra autoconf check?

**Comment by rcombs** [comment] 2024-10-13 18:54
What are the recommended macro checks for *SDK* version? I couldn't find anything for that. `__MAC_OS_X_VERSION_MAX_ALLOWED` is meant to be set by the project, as far as I'm aware (it isn't predefined by the compiler, at least), so I'm not sure how it helps here.

> Old machines have old SDKs.

If you're trying to *build* modern software using ancient toolchains, I don't think it's reasonable to expect things to work out of the box? Actually, wait, Harfbuzz requires C++11 and 10.5 is from 2007; how is this build working at all?

But also, we're talking about an OS version that received its last security patch in 2009; supposing this is the last macOS version supported on the user's machine, and they want to run modern software online (as opposed to taking a historical-preservation focus aimed at the software of the time), I'd imagine they'd be dramatically better-served running Linux (where modern distros don't really *support* the somewhat-esoteric CPU architecture these machines ran on, but some builds do remain available).

**Comment by TheOneric** [comment] 2024-10-13 19:04
> Actually, wait, Harfbuzz requires C++11 and 10.5 is from 2007; how is this build working at all?

The used _compiler_ is a (possibly patched) build of gcc 7.5, released in November 2019 *(see toolchain details in original post)*. But to use system features like CoreText, the SDK/headers shipped with the system need to be used.

**Comment by astiob** [comment] 2024-10-13 19:16
@toreonify FYI the order of the conditional clauses is specifically designed to use the newer code at runtime when a libass build supports _both_ 10.5 and 10.6+, so we don’t want to reorder them or to disable the newer code at all if it can be compiled. We’re being overzealously defensive there, but the old code might stop working—or just work badly—in newer versions of macOS.

---

> `__MAC_OS_X_VERSION_MAX_ALLOWED` is meant to be set by the project

Technically yes, but IIRC we somehow concluded that it wasn’t actually settable at all except manually via an env var and thus effectively always used the SDK’s default value.

But I take it you’re in favour of Autoconf, then? I agree that it’s safer, so I don’t mind.

> Harfbuzz requires C++11 and 10.5 is from 2007; how is this build working at all?

By the power of GCC and libstdc++! But Core Text isn’t open-source, so you can’t just make your own build of a newer version.

I firmly believe that it isn’t our job to decide what environment is best for someone to use. Nobody said this is the user’s primary internet-facing machine, either. Supporting 10.5 was cheap and should cost us nothing at all once we just get the checks right—admittedly, we should’ve done that the first time around, and clearly we failed, and it’s costing us some time now. But still, it’s not like we have a large unmaintainable, untested, keeps-breaking-the-build 10.5-specific code base here.

**Comment by toreonify** [comment] 2024-10-13 19:28
@rcombs GNU\Linux is not great on big-endian CPUs. Especially graphics drivers, so that's why I'm trying to build as much as I can in Mac OS. I like building software from source and it's a good practice for me, especially on old or unsupported configurations.

@TheOneric I even had built a GCC 13 cross-compiler that successfully compiled FFmpeg, though linking was a mess. So yeah, that's not a problem.

@astiob Oh, that's why this code felt weird :) Thanks for an explanation.
I'm amazed that a lot of projects have such a great support for different OSes and yours is one of them.

**Comment by rcombs** [comment] 2024-10-13 19:29
> Technically yes, but IIRC we somehow concluded that it wasn’t actually settable at all except manually via an env var and thus effectively always used the SDK’s default value.

AFAICT the SDK's default value isn't reliably useful either; the 10.5 SDK appears default it to 10.6 in at least some cases: https://github.com/alexey-lysiuk/macos-sdk/blob/cee99e5c64d8e62362331d3f6d911559ba56555d/MacOSX10.5.sdk/usr/include/AvailabilityInternal.h#L63

Generally, Apple headers don't really expect people to support building against older SDKs while also optionally using features from newer ones; they expect the minimum required SDK to also be the one that introduced the latest APIs being used.

> But I take it you’re in favour of Autoconf, then?

Yeah, I think it's the only thing that's going to be fully reliable here, since the 10.5 SDK's headers don't seem to reliably give a version signal.

> But Core Text isn’t open-source, so you can’t just make your own build of a newer version.

Sure, that's true for the binaries used at runtime, but if using a newer compiler, is there any reason not to use newer SDK headers as well?

**Comment by astiob** [comment] 2024-10-13 19:43
Also, personally, I find it _fun_ to add these little pieces that support a whole other platform, even if it costs me time. I understand that this isn’t everyone’s cup of tea, and that’s fine, too.

> GNU\Linux is not great on big-endian CPUs. Especially graphics drivers, so that's why I'm trying to build as much as I can in Mac OS.

Thanks for explaining this motivation! I always suspect that there may be more reasons than meet the eye to use something that seems weird to us, but it’s great to hear what they are.

> the 10.5 SDK appears default it to 10.6 in at least some cases

Oh no. Good catch. Configure-time check it 100% is, then.

I’ll try to whip one up. Guess I’ll need to learn a bit of meson, too.

I’m still baffled as to how this has apparently worked in earlier tests, though. There’s gotta be an SDK difference of some kind.

> Sure, that's true for the binaries used at runtime, but if using a newer compiler, is there any reason not to use newer SDK headers as well?

Oh, that’s an interesting question. I’ll be honest: I hadn’t even considered this.

Indeed, the SDK headers are publicly available, after all, and setting the `MIN_REQUIRED` version should ensure that the code still works at runtime. Some unnecessary code might get compiled, but it’s not usually huge.

I suspect that a big part of this is that, like me, people simply don’t think of this option, but also, using an older (exactly matching) SDK is probably safer for building third-party code that _doesn’t_ go the extra mile to support `MIN_REQUIRED` like we do and instead just hardcodes the latest calls it spots as declared symbols in headers? Linker checks should help with that, but it’s not implausible that some projects might be using compile-only checks. Ultimately, you’d be trading off some projects that build only with newer SDKs for others that only build with older ones.

**Comment by astiob** [comment] 2024-10-13 20:02
> Oh no. Good catch. Configure-time check it 100% is, then.

(I suppose we could still use the macro from `AvailabilityMacros`, which does default to 1050, but sure.)

**Comment by astiob** [comment] 2024-10-13 20:09
Or indeed we could just use `MAC_OS_X_VERSION_10_6` from `AvailabilityMacros.h` in our current preprocessor check, hmm.

Say, what’s the plan for the 10.9 and 10.15 checks in #607 after this? The 10.9 one can probably be replaced by `defined(__OSX_AVAILABLE_STARTING)`, but for 10.15, also configure-time? If not and if we want to keep it `#ifndef __MAC_10_15` as it is now, then maybe going with `#ifdef MAC_OS_X_VERSION_10_6` here would be good for consistency, actually?

**Comment by rcombs** [comment] 2024-10-14 06:28
Hmm, yeah, I guess `MAC_OS_X_VERSION_10_6` ought to work; weird that there's a distinction between that and `__MAC_10_6` being defined at all, but I guess we can roll with it.

**Comment by barracuda156** [comment] 2024-10-14 06:58
> @barracuda156 Could you help here? Does your 10.5 SDK define `__MAC_10_6` in `Availability.h`?

@astiob Thanks for tagging me.

SDKs on the GH repo referred above is canonical, AFAIK. It won’t include 10.6 ppc (10a190) SDK, obviously, but 10.5.8 should be the one from Apple.

Now after your question, I am thinking which one was chosen: there is a slight variation between the one from Xcode 3.1.4 and the one from 3.2.6/4.2 – both have bugs in fact but different ones – however those should be of no consequence here.
It is possible by the way that `__MAC_10_6` is defined in 10.5 SDK which shipped with Xcode for 10.6. Then, there are two different Xcodes for 10.6: 3.2.6 and 4.2. I am not sure their 10.5 SDK are strictly identical either.

I cannot check what my installation has, since I am away from the hardware for about 10 more days. It should be possible to verify exactly if any relevant differences exist by extracting 10.5 SDK from images of Xcode 3.1.4, Xcode 3.2.6 and Xcode 4.2 (with Pacifist or via a procedure described in XcodeLegacy repo, for example).
I can update on this once I am back.

@rcombs Internal headers should not be used by third party software at all. The canonical way is using `AvailabilityMacros.h`, and that one works always correctly, as long as right macros are used.

Notice that `AvailabilityMacros.h` use unprefixed macros, i.e. correct check is `MAC_OS_X_VERSION_MIN_REQUIRED < 1060` etc. (without leading underscores).

**Comment by barracuda156** [comment] 2024-10-14 07:11
> Actually, wait, Harfbuzz requires C++11 and 10.5 is from 2007; how is this build working at all?

Even C++23 works on 10.5–10.6 on PowerPC with a few exceptions caused by usage of the old ABI (which is forced for now as a hack until gcc upstream makes a fix for the issue). On that see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=116777

> The used _compiler_ is a (possibly patched) build of gcc 7.5, released in November 2019 _(see toolchain details in original post)_. But to use system features like CoreText, the SDK/headers shipped with the system need to be used.

Just in case, while MacPorts at the moment (and indefinitely) is stuck at gcc 7.5, as of now the latest gcc builds and works on older macOS, reportedly back to 10.4.11.
So at least on 10.5–10.6 we can have gcc 14 or gcc 15. That may introduce some differences in behavior, at least potentially.

**Comment by barracuda156** [comment] 2024-10-14 07:19
> (I suppose we could still use the macro from `AvailabilityMacros.h`, which does default to 1050, but sure.)

`AvailabilityMacros.h` is the standard way for these cases, and AFAIK it never fails (as long as macros are used correctly, which is not always the case in open-source projects).

**Comment by toreonify** [comment] 2024-10-14 07:24
> It should be possible to verify exactly if any relevant differences exist by extracting 10.5 SDK from images of Xcode 3.1.4, Xcode 3.2.6 and Xcode 4.2 (with Pacifist or via a procedure described in XcodeLegacy repo, for example).

@barracuda156 I can download these versions and check for differences in 10.5 SDK for each version and post results here. I have Pacifist already on my machine, so it won't be a problem.

**Comment by barracuda156** [comment] 2024-10-14 07:24
> Sure, that's true for the binaries used at runtime, but if using a newer compiler, is there any reason not to use newer SDK headers as well?

@rcombs Yes, of course: no SDK after 10.14 supports i386, no SDK after 10.6 supports ppc and no SDK after 10.5 supports ppc64. So it just won’t work at least in these cases. That will require to complicate the code with yet more fallbacks, with no benefit and possible adverse effects (who knows what Apple has tested and what was simply assumed to work).

**Comment by astiob** [comment] 2024-10-14 11:12
> Internal headers should not be used by third party software at all. The canonical way is using `AvailabilityMacros.h`

We’re using `Availability.h`, which is hardly internal. It adds support for iOS and other platforms, which `AvailabilityMacros.h` lacks.

**Comment by barracuda156** [comment] 2024-10-14 11:26
> > Internal headers should not be used by third party software at all. The canonical way is using `AvailabilityMacros.h`
> 
> We’re using `Availability.h`, which is hardly internal. It adds support for iOS and other platforms, which `AvailabilityMacros.h` lacks.

@astiob Yeah, I rather referred to `AvailabilityInternal.h` which was mentioned in passing above.

BTW, `Availability.h` does not exist in 10.4, so using it leaves broken the build on Tiger. (This is not my personal concern, but there are people using Tiger on older hardware.)

**Comment by astiob** [comment] 2024-10-14 11:28
> It should be possible to verify exactly if any relevant differences exist by extracting 10.5 SDK from images of Xcode 3.1.4, Xcode 3.2.6 and Xcode 4.2

Hmm. I have old copies of 3.1.4, 3.2.1 (several), 3.2.2 and 3.2.6 lying around, and it turns out that all of them, even 3.1.4 (xcode314_2809_developerdvd.dmg), already contained a definition of `__MAC_10_6` in MacOSX10.5.sdk. I’ve just downloaded 3.1.3 and 3.1[.0] from Apple’s archive, and they contain it, too. The next older version is 2.5, which lacks MacOSX10.5.sdk entirely.

Could it be that PPC Leopard shipped with a system header that differed from Xcode’s? or with a different Xcode build that isn’t available in Apple’s archive?

**Comment by astiob** [comment] 2024-10-14 11:30
> Yeah, I rather referred to `AvailabilityInternal.h` which was mentioned in passing above.

It’s just transitively included by `Availability.h`—and in newer SDKs, by `AvailabilityMacros.h` too—so some definitions are located inside it.

> BTW, `Availability.h` does not exist in [10.4](https://github.com/alexey-lysiuk/macos-sdk/tree/cee99e5c64d8e62362331d3f6d911559ba56555d/MacOSX10.4u.sdk/usr/include), so using it leaves broken the build on Tiger. (This is not my personal concern, but there are people using Tiger on older hardware.)

Tiger lacks Core Text entirely, so this module is not attempted to be built there.

**Comment by barracuda156** [comment] 2024-10-14 11:37
> > It should be possible to verify exactly if any relevant differences exist by extracting 10.5 SDK from images of Xcode 3.1.4, Xcode 3.2.6 and Xcode 4.2
> 
> Hmm. I have old copies of 3.1.4, 3.2.1 (several), 3.2.2 and 3.2.6 lying around, and it turns out that all of them, even 3.1.4 (xcode314_2809_developerdvd.dmg), already contained a definition of `__MAC_10_6` in MacOSX10.5.sdk. I’ve just downloaded 3.1.3 and 3.1[.0] from Apple’s archive, and they contain it, too. The next older version is 2.5, which lacks MacOSX10.5.sdk entirely.

Thank you for checking this!

This looks like a bug in the SDK, take a look here: https://trac.macports.org/wiki/LeopardSDKFixes
(For the record, recommendation to replace the dylib there is questionable at best, but Availability-related note appears perfectly valid.)

> Could it be that PPC Leopard shipped with a system header that differed from Xcode’s? or with a different Xcode build that isn’t available in Apple’s archive?

AFAIK, Xcode 3.1.4 is identical and perhaps no one would be using some exotic earlier builds (which may be around in principle) on 10.5.8, there is no reason to do that.

**Comment by barracuda156** [comment] 2024-10-14 12:16
@astiob P. S. Since we can’t really advise users to modify system headers (I doubt even MacPorts users do that, as it is nowhere obvious), the only way is to have a workaround for 10.5. (This issue is a surprise to me either, since I nearly exclusively use 10.6 on my powerpc machines, so I have never bumped into it.)

**Comment by toreonify** [comment] 2024-10-14 15:25
> Anyway, @toreonify, can you verify whether [45a9e71](https://github.com/libass/libass/commit/45a9e710016e4f17d8bfd8fea47f83a8247b2f13) fixes this for you?

Yup, build completes without any errors! I'll pack it locally to a port later to compile from MacPorts. Thank you so much for a fix! Didn't expect such involvement :)

> @toreonify Completely unrelated to the issue discussed here, but I noticed you use `ld64-127 +llvm33` on your system; it is generally held that `ld64-97` works better across powerpc macOS, including Leopard (i.e. this is my personal conclusion as well, but also opinion of MacPorts upstream). You may wish to use that linker instead. It may be worth switching to `+llvm34` as well, but I have no hard evidence it gonna improve performance, rather that it is safe to use.

Thank you for a recommendation! I'll definitely try it.

**Closed** 2024-10-15 11:19 UTC
Labels: build, macos
