### ISSUE TITLE
ScaledBorderAndShadow should default to “no”

### ISSUE THREAD

**Issue by kyuunbe** [libass/libass#287] opened 2017-10-23 02:04 UTC
**Subitle resolution:** 384x288
**Video resolution:** 1920x1080
**Style:** Arial Rounded MT Bold, size=17, border=3

**VSFilter (Aegisub and MPC-HC):**
![mpc-hc64_2017-10-22_19-55-07](https://user-images.githubusercontent.com/33012468/31869101-eebab322-b762-11e7-87d4-663f2a9ea2e0.jpg)

**libass (mpv and VLC)**
![mpv_2017-10-22_19-47-10](https://user-images.githubusercontent.com/33012468/31868987-f066f56a-b761-11e7-80d5-55aa51be2322.jpg)

**Comment by kyuunbe** [comment] 2017-10-23 02:40
**Subitle resolution:** 1280x720
**Video resolution:** 1920x1080
**Style:** Arial Rounded MT Bold, size=40, border=4, shadow=2

**VSFilter (Aegisub and MPC-HC):**
![mpc-hc64_2017-10-22_20-35-57](https://user-images.githubusercontent.com/33012468/31870055-0a87fc6c-b769-11e7-89c0-be490ee0323d.jpg)

**libass (mpv and VLC)**
![mpv_2017-10-22_20-36-05](https://user-images.githubusercontent.com/33012468/31870057-0fd715d6-b769-11e7-8602-e3912f2bb4b0.jpg)

**Comment by astiob** [comment] 2017-10-23 13:12
Does your script have a `ScaledBorderAndShadow` header?

If not, the problem is that libass currently defaults this value to “yes” whereas VSFilter defaults it to “no”, and we’re currently discussing (on IRC) how to fix this without breaking other applications such as mpv and FFmpeg.

Are you the author of the script? If you are, _please_ explicitly _enable_ scaled border and shadow and recalculate your borders and shadows (or change the `PlayResX` and `PlayResY` headers to match the video and recalculate your font sizes instead). This is easier to understand and work with, and also most compatible with old versions of libass and media players using libass (although if your script has complex sign typesetting, then old libass may be broken anyway, so this may not mean much). If you’re using Aegisub, this is controlled by a checkbox in the Script Properties window. But if you really must, you can explicitly disable scaled border and shadow by adding a `ScaledBorderAndShadow: no` header. (I don’t know if Aegisub does this when the checkbox is unchecked.)

**Comment by kyuunbe** [comment] 2017-10-23 22:01
I don't fansub, I'm just a mpv user who noticed that this happens in a lot releases from different fansub groups and it starts to getting annoying when the bords are too big.

Maybe an optional parameter on mpv could fix this? (Like --disableborderandshadowscaling)

**Comment by astiob** [comment] 2018-03-11 22:04
Oh, this is a duplicate of #154. I can’t decide which bug report is better, so let’s keep the older one.

**Comment by astiob** [comment] 2018-03-11 22:06
On second thought, #154 contains two separate issues, so I’ll rather split it and keep this bug for the `ScaledBorderAndShadow` default.

**Closed** 2020-07-05 21:37 UTC
Labels: compatibility

**Comment by avih** [comment] 2020-07-11 17:41
FWIW, this commit made the OSD outline in mpv very thin, and subjectively too thin IMHO. See https://github.com/mpv-player/mpv/issues/7900 .

**Comment by erickyun** [comment] 2021-03-10 13:38
Hi,

The .ass subtitle doesn't look like it suppose to be without adding **ScaledBorderAndShadow :yes** in the .ass subtitle?

I think that for mpv player **ScaledBorderAndShadow: yes** should by default.
Cuz
With android mx player the the subtitle is looking like it suppose to be but with mpv it doesn't. But only when **ScaledBorderAndShadow :yes** is added in .ass subtitle the subtitle looks correct like mx player.
