### ISSUE TITLE
Render fonts that have broken glyph 

### ISSUE THREAD

**Issue by hani-yassine** [libass/libass#379] opened 2020-03-11 21:08 UTC
hello, i'm trying to burn in subtitles using handbrake latest version but the problem if one of the fonts have a broken glyph it show up as square, meanwhile the font play normally in video players such as mpc-h which use vsfilter (the broken glyph show up normally) i even tried another encoding programs that use vsfilter for subs and it did render them normally (in the burned in sub video), hopefully libass can be updated in a way to read fonts that have broken fonts! that will make it a perfect filter i will leave a test sub with 2 font 1 working normally and the other have an error in some glyph showing up as square , test sub + fonts + handbrake log file :
[test.zip](https://github.com/libass/libass/files/4320902/test.zip)
Note the font that have broken glyph is AGA Cairo Regular

**Comment by samoht0** [comment] 2020-03-14 09:05
From what I can see, the problem seems to be on your side. You're trying to use glyphs, that simply aren't included in AGA Cairo Regular (mplayer):

[ass] fontselect: (AGA Cairo Regular, 400, 0) -> AGA-CairoRegular, 0, AGA-CairoRegular
[ass] fontselect: (AGA Cairo Regular, 700, 0) -> AGA-CairoRegular, 0, AGA-CairoRegular
[ass] Glyph 0x643 not found, selecting one more font for (AGA Cairo Regular, 700, 0)
[ass] fontselect: Using default font family: (AGA Cairo Regular, 700, 0) -> /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
[ass] fontselect: (AGA Cairo Regular, 700, 0) -> /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold

As you can see, libass supports font substitution. Maybe some config problem with handbrake. But.. it's just a hack to splice in glyphs from other fonts, unintended. So the only proper option is to fix your script. Maybe doing some research on handbrake's fontconfig is an option too.

I don't see an issue related to libass. Please consider checking / updating your report.

**Comment by hani-yassine** [comment] 2020-03-14 16:15
> From what I can see, the problem seems to be on your side. You're trying to use glyphs, that simply aren't included in AGA Cairo Regular (mplayer):
> 
> [ass] fontselect: (AGA Cairo Regular, 400, 0) -> AGA-CairoRegular, 0, AGA-CairoRegular
> [ass] fontselect: (AGA Cairo Regular, 700, 0) -> AGA-CairoRegular, 0, AGA-CairoRegular
> [ass] Glyph 0x643 not found, selecting one more font for (AGA Cairo Regular, 700, 0)
> [ass] fontselect: Using default font family: (AGA Cairo Regular, 700, 0) -> /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
> [ass] fontselect: (AGA Cairo Regular, 700, 0) -> /usr/share/fonts/dejavu/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
> 
> As you can see, libass supports font substitution. Maybe some config problem with handbrake. But.. it's just a hack to splice in glyphs from other fonts, unintended. So the only proper option is to fix your script. Maybe doing some research on handbrake's fontconfig is an option too.
> 
> I don't see an issue related to libass. Please consider checking / updating your report.

they are not missing video players that use vsfilter for sub can render them normally , i also tried encoding with vsfilter also showed them normally i think libass just dont read fonts if it have an error , according to font forge the error is some letter dont have perfectly connected dots

**Comment by samoht0** [comment] 2020-03-14 18:21
> they are not missing video players that use vsfilter for sub can render them normally [...]

They (Glyphs) are missing, or what do you think that mplayer output means:
> [ass] Glyph 0x643 not found, selecting one more font for (AGA Cairo Regular, 700, 0)

Players *do* select a alternative font from the font family. Handbrake maybe doesn't (perhaps a config option). It's not a libass issue. Libass *does* support selecting one more font, if a script defined font does miss a glyph or is absent.

And as said before, the root problem is, that your script should not use AGA-CairoRegular to display glyphs, that're not included in AGA-CairoRegular. Selecting a alternative font is just a work around, which cause a visual differences, typically breaking typesetting.

**Comment by hani-yassine** [comment] 2020-03-18 22:09
> > they are not missing video players that use vsfilter for sub can render them normally [...]
> 
> They (Glyphs) are missing, or what do you think that mplayer output means:
> 
> > [ass] Glyph 0x643 not found, selecting one more font for (AGA Cairo Regular, 700, 0)
> 
> Players _do_ select a alternative font from the font family. Handbrake maybe doesn't (perhaps a config option). It's not a libass issue. Libass _does_ support selecting one more font, if a script defined font does miss a glyph or is absent.
> 
> And as said before, the root problem is, that your script should not use AGA-CairoRegular to display glyphs, that're not included in AGA-CairoRegular. Selecting an alternative font is just a work around, which causes visual differences, typically breaking typesetting.

download the test and try i tried it my self it doesn't select an alternative font i opened the font and saw the same letters style displayed in the video player (also the video encoding) i used staxrip to hard-code the subs which use vsfilter and it did render them normally

**Comment by TheOneric** [comment] 2021-12-18 01:46
The font does not use a normal Unicode charmap. I'm not sure what charmap it uses though, judging by the warnings fontforge gives me it's possibly not just a "normal" non-Unicode font, but also a symbol font? *(E.g.: “The glyph with name at is mapped to U+F220, but name suggests it should be U+0040”)*. So a duplicate of #319 (or #531 if it isn't a symbol font).

**Closed by TheOneric** 2021-12-18 01:46 UTC

**Comment by astiob** [comment] 2021-12-18 02:28
It’s one of the rare [legacy Arabic fonts](https://docs.microsoft.com/en-us/typography/legacy/legacy_arabic_fonts) that even Microsoft’s documentation says “use not-well-documented mechanisms and legacy shaping implementations”. But hey, there _is_ documentation!

**Comment by astiob** [comment] 2021-12-18 02:32
So this is a duplicate of #292, actually.
