### ISSUE TITLE
can't open font on iOS 18 and tvOS 18 and macOS 15

### ISSUE THREAD

**Issue by debugly** [libass/libass#845] opened 2024-10-30 09:20 UTC
Can't open PingFangUI.ttc which in PrivateFrameworks folder.

```text
[ass] Error opening font: 
'/Library/Developer/CoreSimulator/Volumes/tvOS_22J578/Library/Developer/CoreSimulator/Profiles/Runtimes/tvOS 18.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FontServices.framework/CorePrivate/PingFangUI.ttc
```

Relevant info: 

Because PingFang.ttc font file is missing on iOS 18 and tvOS 18 and macOS 15. 

https://forums.developer.apple.com/forums/thread/758189

**Comment by rcombs** [comment] 2024-10-30 09:44
Unfortunately, Apple now ships a non-standards-compliant version of this font; see FreeType issue at https://gitlab.freedesktop.org/freetype/freetype/-/issues/1281

This issue will likely persist until Apple reverts the change, or releases documentation on the new font format.

**Comment by debugly** [comment] 2024-10-30 09:51
Thank you for your answer.

**Comment by chrisdecker08** [comment] 2024-10-30 15:20
@rcombs I have not verified but it appears to be located at `/System/Library/PrivateFrameworks/FontServices.framework/CorePrivate/PingFangUI.ttc` according to https://forums.developer.apple.com/forums/thread/758189

**Comment by moi15moi** [comment] 2024-10-30 17:59
Duplicate of #828

**Closed** 2024-10-31 18:07 UTC
Labels: fonts, macos, not our bug
