### ISSUE TITLE
Attached fonts issue in 0.15.0

### ISSUE THREAD

**Issue by SSgumS** [libass/libass#496] opened 2021-04-22 05:26 UTC
Hello
I know the problem has been fixed in the next commit of the release. But it caused some problems.
There is lots of ass subtitles that have attached fonts. Unfortunately some players that use libass are using just the released version and ignored next commits. For example VLC. Or I could see some Linux releases of mpv have the problem too. Interestingly some other releases of mpv doesn't have the problem (same version). So I don't know why some releases just use the latest release and some use the latest commit. Don't know where this inconsistency comes from... 
Don't you think it's better to have a minor release on libass? Everyone will be aware of the problem then. It will prevent occurring of the same issue for all players and releases. it's really odd for me that you ignored such a big problem and didn't release a 0.15.1...

A topic in mpv repository according to this issue:
https://github.com/mpv-player/mpv/issues/8560

**Comment by TheOneric** [comment] 2021-04-22 16:27
We do intend to make a [0.1.51 bugfix release](https://github.com/libass/libass/milestone/3) in the near-ish future, but there's more than just embedded fonts to be done for this. Admittedly it takes a bit longer than I initially expected to wrap everything up for 0.15.1. If you can't wait, you could politely ask your package maintainers to backport the embedded font fix (commit: 017137471d0043e0321e377ed8da48e45a3ec632); there are no merge conflicts to 0.15.0.


> For example VLC. […] Interestingly some other releases of mpv doesn't have the problem.

VLC's own builds are not affected btw, they currently still use 0.14.0 and are aware of the emfont regression and are prepared to backport the fix if 0.15.1.
mpv does not provide builds of itself; you'll get the features (and for static builds dependencies) chosen by whoever built your mpv binary.

On a side note: Embedded fonts don't even work in VLC. As far as libass players are concerned they only work in mpv (and potentially mplayer(2)) afaik. This is due to an unrelated much older bug which is also due to be (partially) fixed in 0.15.1.
But using ASS' embedded font isn't advisable anyway. They waste space and don't properly work everywhere even before 0.15.0. Embedding fonts into the **mkv** instead whenever possible is much more preferable.

**Closed by TheOneric** 2021-04-22 16:27 UTC
