### ISSUE TITLE
Subtitle performance issue

### ISSUE THREAD

**Issue by laichiaheng** [libass/libass#324] opened 2018-12-21 05:08 UTC
[A bug from MPV player](https://github.com/mpv-player/mpv/issues/6388)
libass causes frame drops.

**Comment by zc62** [comment] 2019-03-01 22:14
As I pointed out in the original issue, this is not a bug. Definitely it would be a great enhancement if the subtitle rendering efficiency could be further improved, but usually it is advised not to run a too complicated script if your CPU cannot afford that.

**Comment by astiob** [comment] 2020-09-19 15:02
The original report included a log file that mentioned [tohka] DATE A LIVE Director's Cut - 04 (BDRip 1920x1080 x264 FLAC) [4372FD18]. If there are particular subtitle fragments in that file that (still) cause performance issues, it would be great to have them posted individually as new issues. But as is, this issue is very nonspecific to say the least, so I’m closing it.

**Closed by astiob** 2020-09-19 15:02 UTC
