### ISSUE TITLE
Stacking of multiple lines that appear simultaneously, given large enough border offset

### ISSUE THREAD

**Issue by zc62** [libass/libass#333] opened 2019-03-01 22:03 UTC
Originally reported in downstream mpv: https://github.com/mpv-player/mpv/issues/6425

An example:
```
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Georgia,60,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,3,30,0,2,30,30,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Dialogue: 0,0:00:02.00,0:00:07.00,Default,,0,0,0,,Neque porro quisquam est qui dolorem ipsum quia dolor.
Dialogue: 0,0:00:04.00,0:00:09.00,Default,,0,0,0,,Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.
```
libass renders like this:
![](https://user-images.githubusercontent.com/17048823/53612557-d40def80-3ba0-11e9-86a2-382c6d4038b5.png)

XySubFilter avoids the overlapping:
![](https://user-images.githubusercontent.com/17048823/53612588-f6a00880-3ba0-11e9-9bc0-cd61c1a56803.png)

**Comment by astiob** [comment] 2020-05-03 14:07
Duplicate of #304; but thanks for the example and screenshots!

**Closed by astiob** 2020-05-03 14:07 UTC
