### ISSUE TITLE
Rendering: Decimal number with \b cause problem

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#669] opened 2022-12-21 15:00 UTC
### Screenshots

Libass
![image](https://user-images.githubusercontent.com/80980684/208934309-ca12495b-e073-45d6-80c4-0eec74bb111d.png)

VSFilter
![image](https://user-images.githubusercontent.com/80980684/208934368-8c1df06f-edb0-454b-92bc-606f2dc167bd.png)

### Description of the issue

VSFilter take the font with the weight 400, but libass take the font with the weight 700

### libass version

AegisubDC 9214

### Is it a regression?

No

### ASS Sample

```
[Script Info]
; Script generated by Aegisub 9214, Daydream Cafe Edition [Shinon]
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 720
PlayResY: 480

[Aegisub Project Garbage]
Video File: ?dummy:23.976000:10000:720:480:16:145:190:
Video AR Value: 1.500000
Video Zoom Percent: 1.500000

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Verdana,35,&H00FFFFFF,&H000000FF,&H002C2C2C,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,0,2,0,0,72,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\b0.9}Example
```

### Special Fonts

[Font.zip](https://github.com/libass/libass/files/10278758/Font.zip)

### System Information

OS: Windows
CPU: 64bits Intel x86

**Comment by rcombs** [comment] 2022-12-21 17:35
What libass version are you using? I can't reproduce this on 062d4ec598b4fd06f75c0cd6a0f43f5d0939a764 (current master). Recent versions print the git hash and version number in the log on renderer init (look for `libass source: […]`).

**Comment by moi15moi** [comment] 2022-12-21 18:12
I used Aegisub 9214.

I have no idea how I can get the version of libass it use.

**Comment by rcombs** [comment] 2022-12-21 18:14
We can't diagnose issues without knowing if you're on a current libass. Closing this out as non-reproducible. Contact the developer of your downstream application for further assistance.

**Closed by rcombs** 2022-12-21 18:14 UTC
Labels: compatibility

**Comment by moi15moi** [comment] 2022-12-21 18:27
I found the version: https://github.com/libass/libass/commit/962b1a

But since you said it doesn't happen on new version, everything should be fine?

**Comment by rcombs** [comment] 2022-12-21 18:31
That's a very old version, yes; this was likely fixed in the interim.
