### ISSUE TITLE
feature request: add generalized tag for changing font-weight

### ISSUE THREAD

**Issue by daT4v1s** [libass/libass#345] opened 2019-06-04 21:40 UTC
instead of only - `bold` or not - , 
add support for something based on [CSS-font-weights](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) 

for example, fonts with `thin` `light` `semi-bold` `extra-bold` and in-between (`Roboto` `Fira Sans` `Open Sans` `Source Code Pro` `Segoe UI` and also variable fonts)

maybe easier to edit and read
vs having to add the full-font-family every time

**Comment by astiob** [comment] 2019-06-04 21:44
You can already do this with \b, e. g.: \b400

**Comment by daT4v1s** [comment] 2019-06-04 22:04
I have a problem where i installed `Roboto Medium Condensed` 
and all the subtitles containing `Roboto Condensed` (referring to Regular) 
suddenly were rendered in Medium Weight, 
but i don't (yet) know where the actual bug is the Font OS or this library

**Comment by rcombs** [comment] 2019-12-09 07:30
Faux-bold kicks in when the target weight is greater the selected font weight + 150. If you set `\b500` and have only a Regular (400) font installed, you won't get faux-bold; if you set `\b600` you will.
Setting `\b1` is equivalent to setting `\b700` and `\b0` is equivalent to `\b400`. If you set `\b1` and have only Regular (400) and a Medium (500) variants installed (or if you put `Medium` in your `\fn` explicitly), libass will select the Medium variant _and_ apply faux-bold.

I can't reproduce the image in your post. Could you provide a full script, including the style you're using (preferably with each line in a separate event instead of one unwieldy one) and a script res?

I get this output, which is more or less in line with what I'd expect:
![image](https://user-images.githubusercontent.com/819638/70415877-068a3880-1aa1-11ea-9eec-34b16ade6076.png)

**Comment by astiob** [comment] 2020-04-02 22:19
This couldn’t be reproduced and seems to work correctly, so I’m closing this. If anyone can reproduce the issue above, please comment.

**Closed by astiob** 2020-04-02 22:19 UTC
