### ISSUE TITLE
Freeze in frame immediately before drawings(?)

### ISSUE THREAD

**Issue by wiiaboo** [libass/libass#158] opened 2015-01-23 01:27 UTC
Sample:
https://i.fsbn.eu/cut.mkv

mpv log with -v -v --no-config:
https://gist.github.com/wiiaboo/0f1400f6e33b4bd28ab6#file-gkd-txt-L4476

freeze happens around line 4476, lasts for about 2-3 seconds.

Haven't tried with latest commit yet. Last compiled mpv yesterday.

**Comment by rcombs** [comment] 2015-01-23 01:35
Duplicate of https://github.com/libass/libass/issues/9

**Closed by rcombs** 2015-01-23 01:35 UTC
