### ISSUE TITLE
wrong blurring strength with outline widths relative to 0.25 and video/script resolution

### ISSUE THREAD

**Issue by Akemi** [libass/libass#309] opened 2018-06-07 11:34 UTC
certain combinations of video/script resolutions and outline widths relative to 0.25 cause the blurring to be scaled wrongly/too strong. the base outline the bug occurs at seems to be 0.25, see tests below.

screenshots were done with following mkv file and external ass file. only the outline width was adjusted for the tests. the bug can be seen at the top and the line "test".
sample: https://0x0.st/s12c.mkv
minimal ass sample: https://0x0.st/s_9S.ass

# **Expected Result**
**outline width 0.25, 1280x720 video/script resolution, window size 1280x720**
![s12c_ 00-00-02 100 _01](https://user-images.githubusercontent.com/680386/41095937-573f0c92-6a53-11e8-92b0-3c7421842180.jpeg)

# **Actual Result with different outline widths and rendering resolutions**
with an outline width of 0.25 any ass render resolution <1280x720 causes the blur to be scaled wrongly, that leads to much more blurring than intended.
**outline width 0.25, 1280x720 video/script resolution, window size slightly smaller 1271x715**
![s12c_ 00-00-02 100 _02](https://user-images.githubusercontent.com/680386/41095934-570c0e3c-6a53-11e8-98fa-8f89d023e6b6.jpeg)

with an outline width of 0.33 this happens around a resolution of 969x545. roughly 76% (969/1280=0.75703125) of the original resolution. which aligns with 0.25/0.33=0.7575757576.
**outline width 0.33, 1280x720 video/script resolution, window size 969x545**
![s12c_ 00-00-02 478 _01](https://user-images.githubusercontent.com/680386/41096132-f851f27a-6a53-11e8-9dd4-020d72d72db8.jpg)

the same can be observed with <0.25 outline width and higher resolutions. with an outline of 0.2 the wrong blurring occurs up to an resolution of around 1598x899. roughly 125% (1598/1280=1.2484375) of the original resolution. which also aligns with 0.25/0.2=1.25.
**outline width 0.2, 1280x720 video/script resolution, window size 1598x899**
![s12c_ 00-00-02 100 _04](https://user-images.githubusercontent.com/680386/41097109-25ef58fa-6a57-11e8-98dd-d88e4506b2cb.jpg)

the same can be observed with outlines >=1.0 and a render size of 1/4 of the original resolution (0.25/1=0.25).

this was original reported on https://github.com/mpv-player/mpv/issues/5715.

**Comment by astiob** [comment] 2018-06-07 12:01
Thanks, although this is a duplicate of #308. I suppose I should have edited the title of that issue when I found its cause, sorry. You’ve provided a better title, description and screenshots, so let’s keep this issue open and close the other one.

Quoting myself:

> Commit 49eb2d2ecdc12d2dcd3af8ca00067cb4161679ff [broke it](https://github.com/libass/libass/commit/49eb2d2ecdc12d2dcd3af8ca00067cb4161679ff#diff-0348e387624211dd40e575fe75ab8596R1087). Commit 856663b2e50017f5ccd5ef284587d8444b0cee38 from #285 fixes it probably by accident, and commit 926fae558d001ab8bc6d3837c5a6a220754a385b also from #285 fixes this for good.
>
> The border width is so small that libass thinks there isn’t any border and blurs the whole thing.

So this should be fixed when I finish reviewing and merge #285. @MrSmile says he’s fixed what he could, so hopefully this is just waiting for my final review now and will be merged soon.

**Comment by Akemi** [comment] 2018-06-07 13:31
oh, thx. sry that i overlooked the issue. nice that it has already been fixed with a PR.

**Closed** 2019-05-20 19:59 UTC
