### ISSUE TITLE
Should cache glyphs that failed to render

### ISSUE THREAD

**Issue by ghost** [libass/libass#186] opened 2015-07-17 10:55 UTC
Sometimes there are broken subtitles (wrong encoding etc.) which contain codepoints that can't be renderer, for example because they're invalid and no font has them.

This causes major performance issues. I'm not sure why, but I suspect fontconfig is slow on lookup, and it happens every frame.

libass should cache failures as well, instead of retrying each frame.

Related: https://github.com/mpv-player/mpv/issues/2143 (although strictly speaking that's not a subtitle).

**Comment by grigorig** [comment] 2015-07-17 11:27
Agreed. I should fix this.

**Comment by wiiaboo** [comment] 2015-09-08 01:37
I don't get any dropped frames with the video. Maybe it's fixed?

**Comment by grigorig** [comment] 2015-09-08 08:33
No it is not. Maybe your PC is too fast.

**Comment by TheOneric** [comment] 2021-12-18 01:25
Duplicate of #137

**Closed by TheOneric** 2021-12-18 01:25 UTC
Labels: performance, fonts
