### ISSUE TITLE
Request: Rounded Subtitle Background

### ISSUE THREAD

**Issue by addisonxx** [libass/libass#848] opened 2024-11-10 02:59 UTC
I would like to have the option to edit the corner radius of the border for the background of subtitles. I originally started looking for a way to accomplish this through IINA, then MPV, and now finally this library because I believe all the other services build off this one. I'm really hoping this could be added because it's such a small feature that doesn't seem super difficult to implement, but would make a major difference for me. I have been having to use HTML players to be able to use the CSS border-radius property to change the background. I really like the modern look of the rounded corners, so when I have to view ones with sharp edges it really stands out and distracts me.

**Comment by rcombs** [comment] 2024-11-10 03:23
Usually we don't do new custom features, but we have a libass-only opaque-box feature anyway, and tbh I think it'd be entirely reasonable to just always round its corners (or to add this as a similar mode). We could do it either drawing a box glyph and using the usual stroker, or in bitmap space (by expanding by r, then clearing sqrt(r-y^2) pixels from each row where y<r, repeat for each corner).

**Comment by addisonxx** [comment] 2024-11-10 03:36
Yes I'd be okay to simply have an option to always round the corners too! Would that still work if the background isn't technically fully opaque? I'm hoping for it to look something like this: a box with 50% opacity background, 15px rounded corners, and approx 5px padding around the text

![TheBear-S2E8Bolognese-15’59”](https://github.com/user-attachments/assets/9cafdeaf-332c-46a5-81ca-7bcefb9dffcf)

**Comment by moi15moi** [comment] 2024-11-10 06:40
Duplicate of https://github.com/libass/libass/issues/688

**Closed** 2024-11-11 22:31 UTC
Labels: duplicate, request
