### ISSUE TITLE
Strange rendering errors on OS X with CoreText-enabled HarfBuzz and AAT fonts

### ISSUE THREAD

**Issue by wm4** [libass/libass#212] opened 2016-01-14 17:12 UTC
This was "found" with mpv's OSD renderer (which uses libass to render text and other stuff).

It works when forcing fontconfig.

```
[Script Info]
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 512
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: progbar,sans-serif,22,&H00ffffff,&H00ffffff,&H00000000,&H7ff0f0f0,0,0,0,0,100,100,0,0,1,1.200000,0,7,10,10,8,1
Style: OSD,sans-serif,22,&H00ffffff,&H00ffffff,&H00000000,&H7ff0f0f0,0,0,0,0,100,100,0,0,1,1.200000,0,7,10,10,8,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:02.00,progbar,,0,0,0,,{\an6\pos(60.150002,241.089996)}
Dialogue: 0,0:00:00.00,0:00:02.00,progbar,,0,0,0,,{\bord0\pos(64.000000,208.649994)}{\p4} m 0 0 l 15 0 l 15 72 l 0 72{\p0}
Dialogue: 0,0:00:00.00,0:00:02.00,progbar,,0,0,0,,{\pos(64.000000,236.589996)}{\p4} m -6 -6 l 3078 -6 l 3078 78 l -6 78 m 0 0 l 0 72 l 3072 72 l 3072 0 m 207 0 l 199 8 l 191 0 m 191 72 l 199 64 l 207 72 m 396 0 l 387 8 l 379 0 m 379 72 l 387 64 l 396 72 m 1375 0 l 1367 8 l 1358 0 m 1358 72 l 1367 64 l 1375 72 m 2828 0 l 2820 8 l 2811 0 m 2811 72 l 2820 64 l 2828 72 m 3017 0 l 3008 8 l 3000 0 m 3000 72 l 3008 64 l 3017 72{\p0}
Dialogue: 0,0:00:00.00,0:00:03.00,OSD,,0,0,0,,osd text
```

http://0x0.st/HmJ.png

**Comment by wm4** [comment] 2016-01-14 17:14
PS: the linked image was made with the libass test program.

Also, if you move the last event to the top, it renders correctly.

**Comment by astiob** [comment] 2016-02-07 22:48
Reduced further:

```
Dialogue: 0,0:00:00.00,0:00:02.00,progbar,,0,0,0,,{\p1} {\p0}
Dialogue: 0,0:00:00.00,0:00:03.00,OSD,,0,0,0,,osd text
```

**Comment by astiob** [comment] 2016-02-08 13:00
Reduced: `{\fnHelvetica\b301\p1} {\p0}text` in any style. `\b` can have any valid argument _except_ numbers in the range from 100 to 300 inclusive.* The drawing text must be nonempty (otherwise the drawing will be skipped entirely by the parser), but it doesn’t have to correspond to an actual nonempty drawing. The drawing must be the first thing set in Helvetica (regardless of the `\b` value).

\* Note: valid `\b` arguments are 0, 1 and integers in the range from 100 to `INT_MAX`.

**Comment by astiob** [comment] 2016-02-08 13:35
Works correctly without harfbuzz.

**Comment by wm4** [comment] 2016-02-08 13:48
Coincides with users reporting that disabling harfbuzz made it work. Not sure if I could reproduce that.

**Comment by Nyx0uf** [comment] 2016-02-08 13:52
Yes I can confirm that disabling harfbuzz solved the problem for me (10.11, / latest libass & mpv)

**Comment by astiob** [comment] 2016-02-08 16:53
In fact, this does happen with Fontconfig as well, but the `\b` value must be 0, 1 or at least 350.

Right now I’m thinking this might be a FreeType bug.

**Comment by astiob** [comment] 2016-02-08 16:59
Indeed, this happens for every .dfont font.

We force a font size of 256 for all text, but drawings keep the real \fs value (scaled from script resolution). When we ask FreeType for the metrics for the first time, it gives us correct metrics for the first glyph’s font size—if the first glyph is a drawing, this is \fs—and for some reason, when we ask it again for later glyphs, it keeps returning the same values instead of the correct values for whatever size the later glyphs have.

**Comment by astiob** [comment] 2016-02-08 17:50
No, FreeType is fine, or at least not broken like that. HarfBuzz _never requests_ the metrics for any of the glyphs! It does with a non-dfont.

**Comment by astiob** [comment] 2016-02-08 18:45
This happens if and only if HarfBuzz is built with CoreText support. It detects that the font has a morx table meant for Apple Advanced Typography and hence delegates shaping to CoreText.

**Comment by astiob** [comment] 2016-02-08 20:55
@behdad In HarfBuzz’s CoreText shaper, `_hb_coretext_shaper_font_data_create` uses `font->x_scale` and `font->y_scale` to compute some internal values and caches the results, and the original scales are not accessed ever again as far as I can tell. In libass, we reuse the same `font` multiple times and call `hb_font_set_scale` before each call to `hb_shape`, possibly with different scales. But as the scale-dependent values are already cached in the `hb_coretext_shaper_font_data_t`, this call makes no difference, and HarfBuzz returns wrongly scaled advance values (correct for the initial font scale but not for the current scale). Is the CoreText shaper buggy or are we misusing it? What can we do to fix this?

**Comment by grigorig** [comment] 2016-02-09 00:14
AFAIR, the native backends (i.e. CoreText and Uniscribe) in HarfBuzz are mostly designed for testing/comparison purposes. That is, to check whether HarfBuzz' shaping engine backend behaves similarly. So maybe it's buggy because of that? You are not supposed to use HarfBuzz' CoreText backend in production.

**Comment by astiob** [comment] 2016-02-09 00:25
It’s still a bug though! :)

HarfBuzz doesn’t support Apple Advanced Typography natively, so when built with Core Text support, it prefers the Core Text backend for fonts with AAT data, even when the backend choice is not forced. (For all other fonts, it prefers its own OpenType backend to Uniscribe, Core Text and DirectWrite.) For the same reason, Homebrew, a major package manager on OS X, builds HarfBuzz with Core Text support.

**Comment by behdad** [comment] 2016-02-09 07:32
That's a hb-coretext bug indeed.  Will get to fix.  Is this urgent or can it wait two / three weeks?  I'm currently travelling and don't have any Mac on me.

**Comment by wm4** [comment] 2016-02-09 07:40
Isn't this the fault of homebrew for enabling code that's only meant for testing? (Didn't check.)

**Comment by behdad** [comment] 2016-02-09 07:54
> AFAIR, the native backends (i.e. CoreText and Uniscribe) in HarfBuzz are mostly designed for testing/comparison purposes.

While that was true when these backends were started, the CoreText one since has been turned into supported one, because Chrome relies on it to shape AAT fonts on Mac platforms.  As such, I like to fix that one at least.

**Comment by behdad** [comment] 2016-02-09 07:55
The core of the problem is that when I was designing the API, I meant a font object to be immutable.  But I failed to enforce that, and people started resizing fonts and reusing them, and it worked with the native shaper, so I decided to support that.  But because of the initial different design, I have font-size-specific data attachment hooks for other backends to use, that I now need to go and clean up.

**Comment by grigorig** [comment] 2016-02-09 09:55
@behdad, does it have any advantage to stick to the initial design goal and never change any font object properties? Maybe performance or something?

**Comment by behdad** [comment] 2016-02-09 10:37
> @behdad, does it have any advantage to stick to the initial design goal and never change any font object properties? Maybe performance or something?

Yes, performance.  And the fact that there is widely-used code out there that I'd be breaking.  So I prefer not to if I don't have to.

Fixing all issues we have with this is easy if users are careful enough to never change anything on the font while another thread is using the same font.  You'd think this is common sense, but I'm sure someone somewhere will fail this assumption and assume that harfbuzz is / should take care of locking for them...  Still trying to think of a way to avoid crashes in those cases.

At any rate, as I said, fixing this particular case (x/y multiplier) is easy, but there are other things that I'm going to add to a font (GX-like variations for example) that are not as easy to fix.

**Comment by astiob** [comment] 2016-02-09 16:06
> Is this urgent or can it wait two / three weeks?

Well, this was first reported to mpv in the first half of December (we’ve only just tracked it down to hb-coretext), and while the issue is certainly unpleasant, I guess the dry fact is another couple of weeks won’t hurt much more. It also happens only in a certain use scenario, reducing the impact. But if you want, I’d be happy to help fixing this in HarfBuzz, whether by testing or by writing a patch.

@wm4 By the way, why does this happen only when OSD is activated in mpv right after opening the file? (Assuming I understand the mpv issue correctly.) Won’t the OSD try to render the same ASS and trigger the bug whenever it is activated? Fansubs don’t tend to use any of the affected fonts, so waiting for a fansub line to show up shouldn’t fix it.

**Comment by wm4** [comment] 2016-02-09 16:26
Yes, the playing symbols etc. are from a custom font.

**Comment by behdad** [comment] 2016-02-22 06:22
Should be fixed in harfbuzz master.  Would be nice if someone can test.  I'll make a release later in the week.

**Comment by astiob** [comment] 2016-02-22 11:02
Tested on the samples in this issue. Seems to be fixed! Thanks!

**Closed** 2016-02-22 11:09 UTC
Labels: bug, not our bug, os x
